//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package logger ;import (_e "fmt";_ee "io";_cd "os";_fg "path/filepath";_c "runtime";);

// Error logs error message.
func (_ga WriterLogger )Error (format string ,args ...interface{}){if _ga .LogLevel >=LogLevelError {_abb :="\u005b\u0045\u0052\u0052\u004f\u0052\u005d\u0020";_ga .logToWriter (_ga .Output ,_abb ,format ,args ...);};};

// Trace logs trace message.
func (_ce ConsoleLogger )Trace (format string ,args ...interface{}){if _ce .LogLevel >=LogLevelTrace {_eae :="\u005b\u0054\u0052\u0041\u0043\u0045\u005d\u0020";_ce .output (_cd .Stdout ,_eae ,format ,args ...);};};

// LogLevel is the verbosity level for logging.
type LogLevel int ;

// Info logs info message.
func (_ad ConsoleLogger )Info (format string ,args ...interface{}){if _ad .LogLevel >=LogLevelInfo {_gb :="\u005bI\u004e\u0046\u004f\u005d\u0020";_ad .output (_cd .Stdout ,_gb ,format ,args ...);};};

// Info does nothing for dummy logger.
func (DummyLogger )Info (format string ,args ...interface{}){};

// Warning logs warning message.
func (_g ConsoleLogger )Warning (format string ,args ...interface{}){if _g .LogLevel >=LogLevelWarning {_d :="\u005b\u0057\u0041\u0052\u004e\u0049\u004e\u0047\u005d\u0020";_g .output (_cd .Stdout ,_d ,format ,args ...);};};

// Error does nothing for dummy logger.
func (DummyLogger )Error (format string ,args ...interface{}){};

// Logger is the interface used for logging in the unipdf package.
type Logger interface{Error (_ff string ,_ea ...interface{});Warning (_a string ,_ed ...interface{});Notice (_cb string ,_cba ...interface{});Info (_fe string ,_ffb ...interface{});Debug (_cbac string ,_eaf ...interface{});Trace (_ca string ,_eeg ...interface{});
IsLogLevel (_cbaf LogLevel )bool ;};

// Notice logs notice message.
func (_fgf ConsoleLogger )Notice (format string ,args ...interface{}){if _fgf .LogLevel >=LogLevelNotice {_af :="\u005bN\u004f\u0054\u0049\u0043\u0045\u005d ";_fgf .output (_cd .Stdout ,_af ,format ,args ...);};};

// IsLogLevel returns true if log level is greater or equal than `level`.
// Can be used to avoid resource intensive calls to loggers.
func (_da WriterLogger )IsLogLevel (level LogLevel )bool {return _da .LogLevel >=level };

// NewConsoleLogger creates new console logger.
func NewConsoleLogger (logLevel LogLevel )*ConsoleLogger {return &ConsoleLogger {LogLevel :logLevel }};

// Warning logs warning message.
func (_ade WriterLogger )Warning (format string ,args ...interface{}){if _ade .LogLevel >=LogLevelWarning {_ag :="\u005b\u0057\u0041\u0052\u004e\u0049\u004e\u0047\u005d\u0020";_ade .logToWriter (_ade .Output ,_ag ,format ,args ...);};};func (_ada WriterLogger )logToWriter (_dbc _ee .Writer ,_ffe string ,_dcd string ,_cgc ...interface{}){_edb (_dbc ,_ffe ,_dcd ,_cgc );
};

// DummyLogger does nothing.
type DummyLogger struct{};

// Error logs error message.
func (_ec ConsoleLogger )Error (format string ,args ...interface{}){if _ec .LogLevel >=LogLevelError {_cg :="\u005b\u0045\u0052\u0052\u004f\u0052\u005d\u0020";_ec .output (_cd .Stdout ,_cg ,format ,args ...);};};

// SetLogger sets 'logger' to be used by the unidoc unipdf library.
func SetLogger (logger Logger ){Log =logger };

// Debug logs debug message.
func (_db ConsoleLogger )Debug (format string ,args ...interface{}){if _db .LogLevel >=LogLevelDebug {_fed :="\u005b\u0044\u0045\u0042\u0055\u0047\u005d\u0020";_db .output (_cd .Stdout ,_fed ,format ,args ...);};};

// Warning does nothing for dummy logger.
func (DummyLogger )Warning (format string ,args ...interface{}){};

// Notice does nothing for dummy logger.
func (DummyLogger )Notice (format string ,args ...interface{}){};

// Notice logs notice message.
func (_ef WriterLogger )Notice (format string ,args ...interface{}){if _ef .LogLevel >=LogLevelNotice {_cag :="\u005bN\u004f\u0054\u0049\u0043\u0045\u005d ";_ef .logToWriter (_ef .Output ,_cag ,format ,args ...);};};

// Trace logs trace message.
func (_gbg WriterLogger )Trace (format string ,args ...interface{}){if _gbg .LogLevel >=LogLevelTrace {_cdd :="\u005b\u0054\u0052\u0041\u0043\u0045\u005d\u0020";_gbg .logToWriter (_gbg .Output ,_cdd ,format ,args ...);};};

// Debug does nothing for dummy logger.
func (DummyLogger )Debug (format string ,args ...interface{}){};func _edb (_bd _ee .Writer ,_df string ,_de string ,_dca ...interface{}){_ ,_fd ,_dbd ,_dfg :=_c .Caller (3);if !_dfg {_fd ="\u003f\u003f\u003f";_dbd =0;}else {_fd =_fg .Base (_fd );};_fgc :=_e .Sprintf ("\u0025s\u0020\u0025\u0073\u003a\u0025\u0064 ",_df ,_fd ,_dbd )+_de +"\u000a";
_e .Fprintf (_bd ,_fgc ,_dca ...);};var Log Logger =DummyLogger {};

// Trace does nothing for dummy logger.
func (DummyLogger )Trace (format string ,args ...interface{}){};

// Debug logs debug message.
func (_cf WriterLogger )Debug (format string ,args ...interface{}){if _cf .LogLevel >=LogLevelDebug {_cec :="\u005b\u0044\u0045\u0042\u0055\u0047\u005d\u0020";_cf .logToWriter (_cf .Output ,_cec ,format ,args ...);};};func (_cad ConsoleLogger )output (_ab _ee .Writer ,_b string ,_ffc string ,_ceb ...interface{}){_edb (_ab ,_b ,_ffc ,_ceb ...);
};

// IsLogLevel returns true from dummy logger.
func (DummyLogger )IsLogLevel (level LogLevel )bool {return true };

// NewWriterLogger creates new 'writer' logger.
func NewWriterLogger (logLevel LogLevel ,writer _ee .Writer )*WriterLogger {logger :=WriterLogger {Output :writer ,LogLevel :logLevel };return &logger ;};

// WriterLogger is the logger that writes data to the Output writer
type WriterLogger struct{LogLevel LogLevel ;Output _ee .Writer ;};

// IsLogLevel returns true if log level is greater or equal than `level`.
// Can be used to avoid resource intensive calls to loggers.
func (_eb ConsoleLogger )IsLogLevel (level LogLevel )bool {return _eb .LogLevel >=level };

// Info logs info message.
func (_ac WriterLogger )Info (format string ,args ...interface{}){if _ac .LogLevel >=LogLevelInfo {_dc :="\u005bI\u004e\u0046\u004f\u005d\u0020";_ac .logToWriter (_ac .Output ,_dc ,format ,args ...);};};const (LogLevelTrace LogLevel =5;LogLevelDebug LogLevel =4;
LogLevelInfo LogLevel =3;LogLevelNotice LogLevel =2;LogLevelWarning LogLevel =1;LogLevelError LogLevel =0;);

// ConsoleLogger is a logger that writes logs to the 'os.Stdout'
type ConsoleLogger struct{LogLevel LogLevel ;};