//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package hyperlinkcolor ;import (_g "encoding/xml";_a "fmt";_e "github.com/unidoc/unioffice/v2";);func (_ffe ST_HyperlinkColor )Validate ()error {return _ffe .ValidateWithPath ("")};func (_ef *CT_HyperlinkColor )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {_ef .ValAttr =ST_HyperlinkColor (1);
for _ ,_ggb :=range start .Attr {if _ggb .Name .Local =="\u0076\u0061\u006c"{_ef .ValAttr .UnmarshalXMLAttr (_ggb );continue ;};};for {_c ,_gc :=d .Token ();if _gc !=nil {return _a .Errorf ("\u0070\u0061r\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005f\u0048\u0079\u0070\u0065\u0072\u006c\u0069\u006e\u006b\u0043\u006f\u006c\u006f\u0072: \u0025\u0073",_gc );
};if _ac ,_cg :=_c .(_g .EndElement );_cg &&_ac .Name ==start .Name {break ;};};return nil ;};func (_da ST_HyperlinkColor )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {return e .EncodeElement (_da .String (),start );};func NewCT_HyperlinkColor ()*CT_HyperlinkColor {_de :=&CT_HyperlinkColor {};
_de .ValAttr =ST_HyperlinkColor (1);return _de ;};type HlinkClr struct{CT_HyperlinkColor };func (_ea *CT_HyperlinkColor )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {_f ,_dg :=_ea .ValAttr .MarshalXMLAttr (_g .Name {Local :"\u0076\u0061\u006c"});
if _dg !=nil {return _dg ;};start .Attr =append (start .Attr ,_f );e .EncodeToken (start );e .EncodeToken (_g .EndElement {Name :start .Name });return nil ;};func (_bc ST_HyperlinkColor )MarshalXMLAttr (name _g .Name )(_g .Attr ,error ){_cb :=_g .Attr {};
_cb .Name =name ;switch _bc {case ST_HyperlinkColorUnset :_cb .Value ="";case ST_HyperlinkColorHlink :_cb .Value ="\u0068\u006c\u0069n\u006b";case ST_HyperlinkColorTx :_cb .Value ="\u0074\u0078";};return _cb ,nil ;};const (ST_HyperlinkColorUnset ST_HyperlinkColor =0;
ST_HyperlinkColorHlink ST_HyperlinkColor =1;ST_HyperlinkColorTx ST_HyperlinkColor =2;);type CT_HyperlinkColor struct{ValAttr ST_HyperlinkColor ;};func (_afd ST_HyperlinkColor )ValidateWithPath (path string )error {switch _afd {case 0,1,2:default:return _a .Errorf ("\u0025s\u003a\u0020\u006f\u0075t\u0020\u006f\u0066\u0020\u0072a\u006eg\u0065 \u0076\u0061\u006c\u0075\u0065\u0020\u0025d",path ,int (_afd ));
};return nil ;};func (_db ST_HyperlinkColor )String ()string {switch _db {case 0:return "";case 1:return "\u0068\u006c\u0069n\u006b";case 2:return "\u0074\u0078";};return "";};func (_dd *HlinkClr )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {_dd .CT_HyperlinkColor =*NewCT_HyperlinkColor ();
for _ ,_fg :=range start .Attr {if _fg .Name .Local =="\u0076\u0061\u006c"{_dd .ValAttr .UnmarshalXMLAttr (_fg );continue ;};};for {_fc ,_be :=d .Token ();if _be !=nil {return _a .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0048\u006c\u0069n\u006b\u0043\u006c\u0072: \u0025\u0073",_be );
};if _cf ,_bea :=_fc .(_g .EndElement );_bea &&_cf .Name ==start .Name {break ;};};return nil ;};func (_cc *ST_HyperlinkColor )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {_bg ,_ff :=d .Token ();if _ff !=nil {return _ff ;};if _gef ,_bcb :=_bg .(_g .EndElement );
_bcb &&_gef .Name ==start .Name {*_cc =1;return nil ;};if _eg ,_ca :=_bg .(_g .CharData );!_ca {return _a .Errorf ("\u0065\u0078\u0070\u0065\u0063\u0074\u0065\u0064\u0020\u0063\u0068a\u0072\u0020\u0064\u0061\u0074\u0061\u002c\u0020\u0067\u006ft\u0020\u0025\u0054",_bg );
}else {switch string (_eg ){case "":*_cc =0;case "\u0068\u006c\u0069n\u006b":*_cc =1;case "\u0074\u0078":*_cc =2;};};_bg ,_ff =d .Token ();if _ff !=nil {return _ff ;};if _dc ,_abb :=_bg .(_g .EndElement );_abb &&_dc .Name ==start .Name {return nil ;};return _a .Errorf ("\u0065\u0078\u0070\u0065c\u0074\u0065\u0064\u0020\u0065\u006e\u0064\u0020\u0065\u006ce\u006de\u006e\u0074\u002c\u0020\u0067\u006f\u0074 \u0025\u0076",_bg );
};

// Validate validates the HlinkClr and its children
func (_cd *HlinkClr )Validate ()error {return _cd .ValidateWithPath ("\u0048\u006c\u0069\u006e\u006b\u0043\u006c\u0072");};

// ValidateWithPath validates the HlinkClr and its children, prefixing error messages with path
func (_af *HlinkClr )ValidateWithPath (path string )error {if _ec :=_af .CT_HyperlinkColor .ValidateWithPath (path );_ec !=nil {return _ec ;};return nil ;};func (_ag *HlinkClr )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068t\u0074\u0070\u003a\u002f\u002f\u0073\u0063he\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d/\u006f\u0066\u0066i\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0038\u002fh\u0079\u0070er\u006c\u0069\u006ek\u0063\u006f\u006c\u006f\u0072"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0068\u006c\u0069\u006e\u006b\u0043\u006c\u0072";return _ag .CT_HyperlinkColor .MarshalXML (e ,start );};func NewHlinkClr ()*HlinkClr {_ab :=&HlinkClr {};_ab .CT_HyperlinkColor =*NewCT_HyperlinkColor ();return _ab ;};func (_deg *ST_HyperlinkColor )UnmarshalXMLAttr (attr _g .Attr )error {switch attr .Value {case "":*_deg =0;
case "\u0068\u006c\u0069n\u006b":*_deg =1;case "\u0074\u0078":*_deg =2;};return nil ;};type ST_HyperlinkColor byte ;

// Validate validates the CT_HyperlinkColor and its children
func (_df *CT_HyperlinkColor )Validate ()error {return _df .ValidateWithPath ("\u0043\u0054\u005f\u0048\u0079\u0070\u0065\u0072\u006c\u0069\u006e\u006bC\u006f\u006c\u006f\u0072");};

// ValidateWithPath validates the CT_HyperlinkColor and its children, prefixing error messages with path
func (_ge *CT_HyperlinkColor )ValidateWithPath (path string )error {if _ge .ValAttr ==ST_HyperlinkColorUnset {return _a .Errorf ("\u0025\u0073\u002fV\u0061\u006c\u0041\u0074t\u0072\u0020\u0069\u0073\u0020\u0061\u0020m\u0061\u006e\u0064\u0061\u0074\u006f\u0072\u0079\u0020\u0066\u0069\u0065\u006c\u0064",path );
};if _b :=_ge .ValAttr .ValidateWithPath (path +"\u002f\u0056\u0061\u006c\u0041\u0074\u0074\u0072");_b !=nil {return _b ;};return nil ;};func init (){_e .RegisterConstructor ("\u0068t\u0074\u0070\u003a\u002f\u002f\u0073\u0063he\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d/\u006f\u0066\u0066i\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0038\u002fh\u0079\u0070er\u006c\u0069\u006ek\u0063\u006f\u006c\u006f\u0072","\u0043\u0054\u005f\u0048\u0079\u0070\u0065\u0072\u006c\u0069\u006e\u006bC\u006f\u006c\u006f\u0072",NewCT_HyperlinkColor );
_e .RegisterConstructor ("\u0068t\u0074\u0070\u003a\u002f\u002f\u0073\u0063he\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d/\u006f\u0066\u0066i\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0038\u002fh\u0079\u0070er\u006c\u0069\u006ek\u0063\u006f\u006c\u006f\u0072","\u0068\u006c\u0069\u006e\u006b\u0043\u006c\u0072",NewHlinkClr );
};