//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package ac ;import (_b "encoding/xml";_c "fmt";_a "github.com/unidoc/unioffice/v2";_fc "github.com/unidoc/unioffice/v2/schema/soo/dml/chart";);func NewMultiLvlStrLit ()*MultiLvlStrLit {_e :=&MultiLvlStrLit {};_e .CT_MultiLvlStrData =*_fc .NewCT_MultiLvlStrData ();
return _e ;};

// Validate validates the MultiLvlStrLit and its children
func (_cd *MultiLvlStrLit )Validate ()error {return _cd .ValidateWithPath ("\u004d\u0075\u006c\u0074\u0069\u004c\u0076\u006c\u0053t\u0072\u004c\u0069\u0074");};func (_g *MultiLvlStrLit )UnmarshalXML (d *_b .Decoder ,start _b .StartElement )error {_g .CT_MultiLvlStrData =*_fc .NewCT_MultiLvlStrData ();
for {_gf ,_gfc :=d .Token ();if _gfc !=nil {return _c .Errorf ("\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u004d\u0075\u006ct\u0069\u004c\u0076\u006c\u0053\u0074\u0072\u004c\u0069\u0074:\u0020\u0025\u0073",_gfc );};if _aa ,_bc :=_gf .(_b .EndElement );
_bc &&_aa .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the MultiLvlStrLit and its children, prefixing error messages with path
func (_gd *MultiLvlStrLit )ValidateWithPath (path string )error {if _eg :=_gd .CT_MultiLvlStrData .ValidateWithPath (path );_eg !=nil {return _eg ;};return nil ;};func (_af *MultiLvlStrLit )MarshalXML (e *_b .Encoder ,start _b .StartElement )error {start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069c\u0065\u002f\u0064\u0072\u0061w\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0034\u002f\u0063\u0068\u0061\u0072\u0074\u002f\u0061\u0063"});
start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u006d\u0075\u006c\u0074\u0069\u004c\u0076\u006c\u0053t\u0072\u004c\u0069\u0074";return _af .CT_MultiLvlStrData .MarshalXML (e ,start );};type MultiLvlStrLit struct{_fc .CT_MultiLvlStrData };func init (){_a .RegisterConstructor ("\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069c\u0065\u002f\u0064\u0072\u0061w\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0034\u002f\u0063\u0068\u0061\u0072\u0074\u002f\u0061\u0063","\u006d\u0075\u006c\u0074\u0069\u004c\u0076\u006c\u0053t\u0072\u004c\u0069\u0074",NewMultiLvlStrLit );
};