//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package powerpoint ;import (_dd "encoding/xml";_a "fmt";_g "github.com/unidoc/unioffice/v2";);

// ValidateWithPath validates the CT_Rel and its children, prefixing error messages with path
func (_db *CT_Rel )ValidateWithPath (path string )error {return nil };func NewIscomment ()*Iscomment {_bb :=&Iscomment {};_bb .CT_Empty =*NewCT_Empty ();return _bb };func (_dbg *Textdata )UnmarshalXML (d *_dd .Decoder ,start _dd .StartElement )error {_dbg .CT_Rel =*NewCT_Rel ();
for _ ,_df :=range start .Attr {if _df .Name .Local =="\u0069\u0064"{_cbd :=_df .Value ;_dbg .IdAttr =&_cbd ;continue ;};};for {_eb ,_cc :=d .Token ();if _cc !=nil {return _a .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0054\u0065\u0078t\u0064\u0061\u0074\u0061: \u0025\u0073",_cc );
};if _ba ,_fec :=_eb .(_dd .EndElement );_fec &&_ba .Name ==start .Name {break ;};};return nil ;};

// Validate validates the Textdata and its children
func (_bab *Textdata )Validate ()error {return _bab .ValidateWithPath ("\u0054\u0065\u0078\u0074\u0064\u0061\u0074\u0061");};type CT_Rel struct{

// Text Reference
IdAttr *string ;};

// Validate validates the Iscomment and its children
func (_de *Iscomment )Validate ()error {return _de .ValidateWithPath ("\u0049s\u0063\u006f\u006d\u006d\u0065\u006et");};func (_f *CT_Rel )MarshalXML (e *_dd .Encoder ,start _dd .StartElement )error {if _f .IdAttr !=nil {start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0069\u0064"},Value :_a .Sprintf ("\u0025\u0076",*_f .IdAttr )});
};e .EncodeToken (start );e .EncodeToken (_dd .EndElement {Name :start .Name });return nil ;};func (_ag *CT_Rel )UnmarshalXML (d *_dd .Decoder ,start _dd .StartElement )error {for _ ,_ae :=range start .Attr {if _ae .Name .Local =="\u0069\u0064"{_ab :=_ae .Value ;
_ag .IdAttr =&_ab ;continue ;};};for {_ea ,_ec :=d .Token ();if _ec !=nil {return _a .Errorf ("\u0070a\u0072s\u0069\u006e\u0067\u0020\u0043T\u005f\u0052e\u006c\u003a\u0020\u0025\u0073",_ec );};if _bc ,_ged :=_ea .(_dd .EndElement );_ged &&_bc .Name ==start .Name {break ;
};};return nil ;};

// Validate validates the CT_Empty and its children
func (_cb *CT_Empty )Validate ()error {return _cb .ValidateWithPath ("\u0043\u0054\u005f\u0045\u006d\u0070\u0074\u0079");};func NewCT_Rel ()*CT_Rel {_gg :=&CT_Rel {};return _gg };type Iscomment struct{CT_Empty };func (_fb *Iscomment )MarshalXML (e *_dd .Encoder ,start _dd .StartElement )error {start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074"});
start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0069s\u0063\u006f\u006d\u006d\u0065\u006et";return _fb .CT_Empty .MarshalXML (e ,start );};func NewTextdata ()*Textdata {_ef :=&Textdata {};_ef .CT_Rel =*NewCT_Rel ();return _ef };func (_gf *CT_Empty )MarshalXML (e *_dd .Encoder ,start _dd .StartElement )error {e .EncodeToken (start );
e .EncodeToken (_dd .EndElement {Name :start .Name });return nil ;};

// ValidateWithPath validates the CT_Empty and its children, prefixing error messages with path
func (_cf *CT_Empty )ValidateWithPath (path string )error {return nil };type Textdata struct{CT_Rel };func NewCT_Empty ()*CT_Empty {_ge :=&CT_Empty {};return _ge };func (_bg *Iscomment )UnmarshalXML (d *_dd .Decoder ,start _dd .StartElement )error {_bg .CT_Empty =*NewCT_Empty ();
for {_ed ,_fe :=d .Token ();if _fe !=nil {return _a .Errorf ("p\u0061\u0072\u0073\u0069ng\u0020I\u0073\u0063\u006f\u006d\u006de\u006e\u0074\u003a\u0020\u0025\u0073",_fe );};if _bd ,_ff :=_ed .(_dd .EndElement );_ff &&_bd .Name ==start .Name {break ;};};
return nil ;};

// ValidateWithPath validates the Iscomment and its children, prefixing error messages with path
func (_agg *Iscomment )ValidateWithPath (path string )error {if _fea :=_agg .CT_Empty .ValidateWithPath (path );_fea !=nil {return _fea ;};return nil ;};

// Validate validates the CT_Rel and its children
func (_aa *CT_Rel )Validate ()error {return _aa .ValidateWithPath ("\u0043\u0054\u005f\u0052\u0065\u006c");};

// ValidateWithPath validates the Textdata and its children, prefixing error messages with path
func (_ac *Textdata )ValidateWithPath (path string )error {if _ddc :=_ac .CT_Rel .ValidateWithPath (path );_ddc !=nil {return _ddc ;};return nil ;};func (_fbd *Textdata )MarshalXML (e *_dd .Encoder ,start _dd .StartElement )error {start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074"});
start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0074\u0065\u0078\u0074\u0064\u0061\u0074\u0061";return _fbd .CT_Rel .MarshalXML (e ,start );};type CT_Empty struct{};func (_e *CT_Empty )UnmarshalXML (d *_dd .Decoder ,start _dd .StartElement )error {for {_b ,_gd :=d .Token ();if _gd !=nil {return _a .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005fE\u006d\u0070\u0074\u0079: \u0025\u0073",_gd );
};if _c ,_gc :=_b .(_dd .EndElement );_gc &&_c .Name ==start .Name {break ;};};return nil ;};func init (){_g .RegisterConstructor ("\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074","\u0043\u0054\u005f\u0045\u006d\u0070\u0074\u0079",NewCT_Empty );
_g .RegisterConstructor ("\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074","\u0043\u0054\u005f\u0052\u0065\u006c",NewCT_Rel );
_g .RegisterConstructor ("\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074","\u0069s\u0063\u006f\u006d\u006d\u0065\u006et",NewIscomment );
_g .RegisterConstructor ("\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074","\u0074\u0065\u0078\u0074\u0064\u0061\u0074\u0061",NewTextdata );
};