//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package sort ;import (_e "regexp";_g "sort";_d "strconv";);func (_gc stringSlice )Less (a ,b int )bool {return NaturalCompare (_gc [a ],_gc [b ])};func MergeSort (array []float64 )[]float64 {if len (array )<=1{_ed :=make ([]float64 ,len (array ));copy (_ed ,array );
return _ed ;};_ca :=len (array )/2;_cf :=MergeSort (array [:_ca ]);_f :=MergeSort (array [_ca :]);_cb :=make ([]float64 ,len (array ));_ga :=0;_a :=0;_fa :=0;for _a < len (_cf )&&_fa < len (_f ){if _cf [_a ]<=_f [_fa ]{_cb [_ga ]=_cf [_a ];_a ++;}else {_cb [_ga ]=_f [_fa ];
_fa ++;};_ga ++;};for _a < len (_cf ){_cb [_ga ]=_cf [_a ];_a ++;_ga ++;};for _fa < len (_f ){_cb [_ga ]=_f [_fa ];_fa ++;_ga ++;};return _cb ;};type stringSlice []string ;func (_b stringSlice )Swap (a ,b int ){_b [a ],_b [b ]=_b [b ],_b [a ]};var _gf =_e .MustCompile ("\u0028\\\u0064\u002b\u007c\u005c\u0044\u002b)");
func NaturalSort (l []string ){_g .Sort (stringSlice (l ))};func (_cc stringSlice )Len ()int {return len (_cc )};func NaturalCompare (a ,b string )bool {_fd :=_gab (a );_fb :=_gab (b );_gd :=len (_fd );_ef :=len (_fb );for _fc :=range _fd {if _fc >=_ef {return false ;
};_fg ,_ce :=_d .Atoi (_fd [_fc ]);_cg ,_df :=_d .Atoi (_fb [_fc ]);if _ce ==nil &&_df ==nil {if _fg ==_cg {if _fc ==_gd -1{return true ;}else if _fc ==_ef -1{return false ;};continue ;};return _fg < _cg ;};if _fd [_fc ]==_fb [_fc ]{if _fc ==_gd -1{return true ;
}else if _fc ==_ef -1{return false ;};continue ;};return _fd [_fc ]< _fb [_fc ];};return false ;};func _gab (_bg string )[]string {return _gf .FindAllString (_bg ,-1)};