//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package symex ;import (_d "encoding/xml";_b "fmt";_a "github.com/unidoc/unioffice/v2";);

// ValidateWithPath validates the SymEx and its children, prefixing error messages with path
func (_ec *SymEx )ValidateWithPath (path string )error {if _gg :=_ec .CT_SymEx .ValidateWithPath (path );_gg !=nil {return _gg ;};return nil ;};func (_gb *CT_SymEx )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {for _ ,_ge :=range start .Attr {if _ge .Name .Local =="\u0066\u006f\u006e\u0074"{_bc :=_ge .Value ;
_gb .FontAttr =&_bc ;continue ;};if _ge .Name .Local =="\u0063\u0068\u0061\u0072"{_e :=_ge .Value ;_gb .CharAttr =&_e ;continue ;};};for {_ea ,_eg :=d .Token ();if _eg !=nil {return _b .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005fS\u0079\u006d\u0045\u0078: \u0025\u0073",_eg );
};if _c ,_ed :=_ea .(_d .EndElement );_ed &&_c .Name ==start .Name {break ;};};return nil ;};

// Validate validates the SymEx and its children
func (_bf *SymEx )Validate ()error {return _bf .ValidateWithPath ("\u0053\u0079\u006dE\u0078")};func (_be *CT_SymEx )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {if _be .FontAttr !=nil {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0073\u003a\u0066\u006f\u006e\u0074"},Value :_b .Sprintf ("\u0025\u0076",*_be .FontAttr )});
};if _be .CharAttr !=nil {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0073\u003a\u0063\u0068\u0061\u0072"},Value :_b .Sprintf ("\u0025\u0076",*_be .CharAttr )});};e .EncodeToken (start );e .EncodeToken (_d .EndElement {Name :start .Name });
return nil ;};func (_bcd *SymEx )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0073:\u0073\u0079\u006d\u0045\u0078";return _bcd .CT_SymEx .MarshalXML (e ,start );};

// Validate validates the CT_SymEx and its children
func (_bb *CT_SymEx )Validate ()error {return _bb .ValidateWithPath ("\u0043\u0054\u005f\u0053\u0079\u006d\u0045\u0078");};type CT_SymEx struct{FontAttr *string ;CharAttr *string ;};func (_fg *SymEx )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {_fg .CT_SymEx =*NewCT_SymEx ();
for _ ,_gc :=range start .Attr {if _gc .Name .Local =="\u0066\u006f\u006e\u0074"{_gea :=_gc .Value ;_fg .FontAttr =&_gea ;continue ;};if _gc .Name .Local =="\u0063\u0068\u0061\u0072"{_gef :=_gc .Value ;_fg .CharAttr =&_gef ;continue ;};};for {_ee ,_cd :=d .Token ();
if _cd !=nil {return _b .Errorf ("\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0053\u0079\u006d\u0045x\u003a\u0020\u0025\u0073",_cd );};if _gbf ,_ad :=_ee .(_d .EndElement );_ad &&_gbf .Name ==start .Name {break ;};};return nil ;};func NewCT_SymEx ()*CT_SymEx {_f :=&CT_SymEx {};
return _f };type SymEx struct{CT_SymEx };

// ValidateWithPath validates the CT_SymEx and its children, prefixing error messages with path
func (_bed *CT_SymEx )ValidateWithPath (path string )error {return nil };func NewSymEx ()*SymEx {_df :=&SymEx {};_df .CT_SymEx =*NewCT_SymEx ();return _df };func init (){_a .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078","\u0043\u0054\u005f\u0053\u0079\u006d\u0045\u0078",NewCT_SymEx );
_a .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078","\u0073\u0079\u006dE\u0078",NewSymEx );
};