//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package decorative ;import (_fg "encoding/xml";_d "fmt";_b "github.com/unidoc/unioffice/v2";_g "strconv";);func (_fc *CT_Decorative )UnmarshalXML (d *_fg .Decoder ,start _fg .StartElement )error {for _ ,_db :=range start .Attr {if _db .Name .Local =="\u0076\u0061\u006c"{_dbf ,_be :=_g .ParseBool (_db .Value );
if _be !=nil {return _be ;};_fc .ValAttr =&_dbf ;continue ;};};for {_e ,_a :=d .Token ();if _a !=nil {return _d .Errorf ("\u0070a\u0072\u0073\u0069\u006eg\u0020\u0043\u0054\u005f\u0044e\u0063o\u0072a\u0074\u0069\u0076\u0065\u003a\u0020\u0025s",_a );};if _dc ,_ff :=_e .(_fg .EndElement );
_ff &&_dc .Name ==start .Name {break ;};};return nil ;};func _bg (_ddc bool )uint8 {if _ddc {return 1;};return 0;};func (_gdg *Decorative )UnmarshalXML (d *_fg .Decoder ,start _fg .StartElement )error {_gdg .CT_Decorative =*NewCT_Decorative ();for _ ,_gc :=range start .Attr {if _gc .Name .Local =="\u0076\u0061\u006c"{_fe ,_dd :=_g .ParseBool (_gc .Value );
if _dd !=nil {return _dd ;};_gdg .ValAttr =&_fe ;continue ;};};for {_dba ,_dgf :=d .Token ();if _dgf !=nil {return _d .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0044\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065\u003a\u0020%\u0073",_dgf );
};if _c ,_fcd :=_dba .(_fg .EndElement );_fcd &&_c .Name ==start .Name {break ;};};return nil ;};

// Validate validates the CT_Decorative and its children
func (_af *CT_Decorative )Validate ()error {return _af .ValidateWithPath ("\u0043\u0054\u005f\u0044\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065");};type CT_Decorative struct{ValAttr *bool ;};func (_dbd *Decorative )MarshalXML (e *_fg .Encoder ,start _fg .StartElement )error {start .Attr =append (start .Attr ,_fg .Attr {Name :_fg .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0037\u002f\u0064\u0065c\u006f\u0072\u0061\u0074\u0069v\u0065"});
start .Attr =append (start .Attr ,_fg .Attr {Name :_fg .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_fg .Attr {Name :_fg .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0064\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065";return _dbd .CT_Decorative .MarshalXML (e ,start );};func NewDecorative ()*Decorative {_da :=&Decorative {};_da .CT_Decorative =*NewCT_Decorative ();return _da ;};

// Validate validates the Decorative and its children
func (_eg *Decorative )Validate ()error {return _eg .ValidateWithPath ("\u0044\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065");};type Decorative struct{CT_Decorative };func NewCT_Decorative ()*CT_Decorative {_bb :=&CT_Decorative {};return _bb };


// ValidateWithPath validates the Decorative and its children, prefixing error messages with path
func (_bef *Decorative )ValidateWithPath (path string )error {if _cc :=_bef .CT_Decorative .ValidateWithPath (path );_cc !=nil {return _cc ;};return nil ;};func (_ge *CT_Decorative )MarshalXML (e *_fg .Encoder ,start _fg .StartElement )error {if _ge .ValAttr !=nil {start .Attr =append (start .Attr ,_fg .Attr {Name :_fg .Name {Local :"\u0076\u0061\u006c"},Value :_d .Sprintf ("\u0025\u0064",_bg (*_ge .ValAttr ))});
};e .EncodeToken (start );e .EncodeToken (_fg .EndElement {Name :start .Name });return nil ;};

// ValidateWithPath validates the CT_Decorative and its children, prefixing error messages with path
func (_bea *CT_Decorative )ValidateWithPath (path string )error {return nil };func init (){_b .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0037\u002f\u0064\u0065c\u006f\u0072\u0061\u0074\u0069v\u0065","\u0043\u0054\u005f\u0044\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065",NewCT_Decorative );
_b .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0037\u002f\u0064\u0065c\u006f\u0072\u0061\u0074\u0069v\u0065","\u0064\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065",NewDecorative );
};