//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package contentblocks ;import (_e "github.com/unidoc/unioffice/v2/common/logger";_f "github.com/unidoc/unioffice/v2/schema/soo/wml";);func Iterate (cbcs []*_f .EG_ContentBlockContent )func (_b func (*_f .EG_ContentBlockContentChoice )bool ){return func (_gf func (*_f .EG_ContentBlockContentChoice )bool ){_ed (cbcs ,_gf ,0)};
};func CountTables (cbcs []*_f .EG_ContentBlockContent )int {_df :=0;for _dg :=range Iterate (cbcs ){_df +=len (_dg .Tbl );};return _df ;};const _g =50;func CountParagraphs (cbcs []*_f .EG_ContentBlockContent )int {_gg :=0;for _fg :=range Iterate (cbcs ){_gg +=len (_fg .P );
};return _gg ;};func _ed (_eg []*_f .EG_ContentBlockContent ,_gc func (*_f .EG_ContentBlockContentChoice )bool ,_fd int )bool {if _fd > _g {_e .Log .Debug ("\u0043o\u006e\u0074e\u006e\u0074\u0042\u006co\u0063\u006b\u0020i\u0074\u0065\u0072\u0061\u0074\u006f\u0072\u0020\u006dax\u0020\u0064\u0065p\u0074\u0068 \u0065\u0078\u0063\u0065\u0065\u0064e\u0064\u003a \u0025\u0064",_fd );
return true ;};for _ ,_a :=range _eg {if _a ==nil ||_a .ContentBlockContentChoice ==nil {continue ;};_c :=_a .ContentBlockContentChoice ;if _ag :=_c .Sdt ;_ag !=nil &&_ag .SdtContent !=nil {if !_ed (_ag .SdtContent .EG_ContentBlockContent ,_gc ,_fd +1){return false ;
};continue ;};if _ege :=_c .CustomXml ;_ege !=nil {if !_ed (_ege .EG_ContentBlockContent ,_gc ,_fd +1){return false ;};continue ;};if !_gc (_c ){return false ;};};return true ;};func Unwrap (cbcs []*_f .EG_ContentBlockContent )[]*_f .EG_ContentBlockContentChoice {var _bf []*_f .EG_ContentBlockContentChoice ;
for _fe :=range Iterate (cbcs ){_bf =append (_bf ,_fe );};return _bf ;};func HasTables (cbcs []*_f .EG_ContentBlockContent )bool {for _cc :=range Iterate (cbcs ){if len (_cc .Tbl )> 0{return true ;};};return false ;};func ForEachTable (cbcs []*_f .EG_ContentBlockContent ,fn func (*_f .CT_Tbl )bool ){for _ee :=range Iterate (cbcs ){for _ ,_bc :=range _ee .Tbl {if !fn (_bc ){return ;
};};};};func ForEachParagraph (cbcs []*_f .EG_ContentBlockContent ,fn func (*_f .CT_P )bool ){for _egc :=range Iterate (cbcs ){for _ ,_fa :=range _egc .P {if !fn (_fa ){return ;};};};};func HasParagraphs (cbcs []*_f .EG_ContentBlockContent )bool {for _ff :=range Iterate (cbcs ){if len (_ff .P )> 0{return true ;
};};return false ;};