//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package scriptlink ;import (_d "encoding/xml";_e "fmt";_gc "github.com/unidoc/unioffice/v2";_g "github.com/unidoc/unioffice/v2/common/logger";_ef "github.com/unidoc/unioffice/v2/schema/soo/dml";);func NewCT_ScriptLink ()*CT_ScriptLink {_ba :=&CT_ScriptLink {};
return _ba };func (_ec *CT_ScriptLink )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {for _ ,_fg :=range start .Attr {if _fg .Name .Local =="\u0076\u0061\u006c"{_fc :=_fg .Value ;_ec .ValAttr =&_fc ;continue ;};};_c :for {_ce ,_fd :=d .Token ();
if _fd !=nil {return _fd ;};switch _ea :=_ce .(type ){case _d .StartElement :switch _ea .Name {case _d .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0031\u002f\u0073\u0063r\u0069\u0070\u0074\u006c\u0069n\u006b",Local :"\u0065\u0078\u0074\u004c\u0073\u0074"}:_ec .ExtLst =_ef .NewCT_OfficeArtExtensionList ();
if _fa :=d .DecodeElement (_ec .ExtLst ,&_ea );_fa !=nil {return _fa ;};default:_g .Log .Debug ("\u0073\u006b\u0069\u0070\u0070\u0069\u006e\u0067 \u0075\u006e\u0073up\u0070\u006f\u0072\u0074\u0065\u0064 \u0065\u006c\u0065\u006d\u0065\u006e\u0074\u0020\u006f\u006e\u0020\u0043\u0054\u005f\u0053c\u0072\u0069\u0070\u0074\u004c\u0069\u006e\u006b \u0025\u0076",_ea .Name );
if _cg :=d .Skip ();_cg !=nil {return _cg ;};};case _d .EndElement :break _c ;case _d .CharData :};};return nil ;};type CT_ScriptLink struct{ValAttr *string ;ExtLst *_ef .CT_OfficeArtExtensionList ;};

// Validate validates the CT_ScriptLink and its children
func (_bf *CT_ScriptLink )Validate ()error {return _bf .ValidateWithPath ("\u0043\u0054\u005f\u0053\u0063\u0072\u0069\u0070\u0074\u004c\u0069\u006e\u006b");};

// ValidateWithPath validates the CT_ScriptLink and its children, prefixing error messages with path
func (_ceb *CT_ScriptLink )ValidateWithPath (path string )error {if _ceb .ExtLst !=nil {if _deb :=_ceb .ExtLst .ValidateWithPath (path +"\u002fE\u0078\u0074\u004c\u0073\u0074");_deb !=nil {return _deb ;};};return nil ;};func (_ced *ScriptLink )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {_ced .CT_ScriptLink =*NewCT_ScriptLink ();
for _ ,_fae :=range start .Attr {if _fae .Name .Local =="\u0076\u0061\u006c"{_ee :=_fae .Value ;_ced .ValAttr =&_ee ;continue ;};};_fga :for {_ed ,_cd :=d .Token ();if _cd !=nil {return _cd ;};switch _dg :=_ed .(type ){case _d .StartElement :switch _dg .Name {case _d .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0031\u002f\u0073\u0063r\u0069\u0070\u0074\u006c\u0069n\u006b",Local :"\u0065\u0078\u0074\u004c\u0073\u0074"}:_ced .ExtLst =_ef .NewCT_OfficeArtExtensionList ();
if _efa :=d .DecodeElement (_ced .ExtLst ,&_dg );_efa !=nil {return _efa ;};default:_g .Log .Debug ("\u0073k\u0069\u0070p\u0069\u006e\u0067 \u0075\u006e\u0073\u0075\u0070\u0070\u006fr\u0074\u0065\u0064\u0020\u0065\u006ce\u006d\u0065\u006e\u0074\u0020\u006f\u006e\u0020\u0053\u0063\u0072i\u0070\u0074\u004c\u0069\u006e\u006b\u0020\u0025\u0076",_dg .Name );
if _gb :=d .Skip ();_gb !=nil {return _gb ;};};case _d .EndElement :break _fga ;case _d .CharData :};};return nil ;};func (_a *ScriptLink )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0031\u002f\u0073\u0063r\u0069\u0070\u0074\u006c\u0069n\u006b"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0073\u0063\u0072\u0069\u0070\u0074\u004c\u0069\u006e\u006b";return _a .CT_ScriptLink .MarshalXML (e ,start );};func (_de *CT_ScriptLink )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {if _de .ValAttr !=nil {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0076\u0061\u006c"},Value :_e .Sprintf ("\u0025\u0076",*_de .ValAttr )});
};e .EncodeToken (start );if _de .ExtLst !=nil {_gd :=_d .StartElement {Name :_d .Name {Local :"\u0065\u0078\u0074\u004c\u0073\u0074"}};e .EncodeElement (_de .ExtLst ,_gd );};e .EncodeToken (_d .EndElement {Name :start .Name });return nil ;};

// Validate validates the ScriptLink and its children
func (_gg *ScriptLink )Validate ()error {return _gg .ValidateWithPath ("\u0053\u0063\u0072\u0069\u0070\u0074\u004c\u0069\u006e\u006b");};

// ValidateWithPath validates the ScriptLink and its children, prefixing error messages with path
func (_def *ScriptLink )ValidateWithPath (path string )error {if _be :=_def .CT_ScriptLink .ValidateWithPath (path );_be !=nil {return _be ;};return nil ;};func NewScriptLink ()*ScriptLink {_cf :=&ScriptLink {};_cf .CT_ScriptLink =*NewCT_ScriptLink ();
return _cf ;};type ScriptLink struct{CT_ScriptLink };func init (){_gc .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0031\u002f\u0073\u0063r\u0069\u0070\u0074\u006c\u0069n\u006b","\u0043\u0054\u005f\u0053\u0063\u0072\u0069\u0070\u0074\u004c\u0069\u006e\u006b",NewCT_ScriptLink );
_gc .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0031\u002f\u0073\u0063r\u0069\u0070\u0074\u006c\u0069n\u006b","\u0073\u0063\u0072\u0069\u0070\u0074\u004c\u0069\u006e\u006b",NewScriptLink );
};