//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package SVG ;import (_d "encoding/xml";_b "fmt";_e "github.com/unidoc/unioffice/v2";);func (_ed *SvgBlip )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069c\u0065\u002f\u0064\u0072\u0061w\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0053\u0056\u0047\u002f\u006d\u0061\u0069\u006e"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0061"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065m\u0061\u0073\u002e\u006f\u0070\u0065\u006e\u0078m\u006cf\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067m\u006c\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0073v\u0067\u0042\u006c\u0069\u0070";return _ed .CT_SVGBlip .MarshalXML (e ,start );};

// Validate validates the CT_SVGBlip and its children
func (_g *CT_SVGBlip )Validate ()error {return _g .ValidateWithPath ("\u0043\u0054\u005f\u0053\u0056\u0047\u0042\u006c\u0069\u0070");};func (_bf *CT_SVGBlip )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {for _ ,_ff :=range start .Attr {if _ff .Name .Space =="\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068\u0065\u006da\u0073\u002e\u006f\u0070\u0065\u006ex\u006d\u006c\u0066\u006f\u0072m\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u006f\u0066\u0066\u0069c\u0065\u0044\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002f\u0032\u0030\u0030\u0036\u002fr\u0065\u006c\u0061\u0074\u0069\u006f\u006e\u0073h\u0069\u0070\u0073"&&_ff .Name .Local =="\u0065\u006d\u0062e\u0064"{_ffg :=_ff .Value ;
_bf .EmbedAttr =&_ffg ;continue ;};if _ff .Name .Space =="\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068\u0065\u006da\u0073\u002e\u006f\u0070\u0065\u006ex\u006d\u006c\u0066\u006f\u0072m\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u006f\u0066\u0066\u0069c\u0065\u0044\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002f\u0032\u0030\u0030\u0036\u002fr\u0065\u006c\u0061\u0074\u0069\u006f\u006e\u0073h\u0069\u0070\u0073"&&_ff .Name .Local =="\u006c\u0069\u006e\u006b"{_bd :=_ff .Value ;
_bf .LinkAttr =&_bd ;continue ;};};for {_fb ,_bg :=d .Token ();if _bg !=nil {return _b .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0043\u0054\u005f\u0053\u0056\u0047\u0042\u006c\u0069\u0070\u003a\u0020%\u0073",_bg );};if _fbf ,_c :=_fb .(_d .EndElement );
_c &&_fbf .Name ==start .Name {break ;};};return nil ;};

// Validate validates the SvgBlip and its children
func (_ca *SvgBlip )Validate ()error {return _ca .ValidateWithPath ("\u0053v\u0067\u0042\u006c\u0069\u0070");};

// ValidateWithPath validates the CT_SVGBlip and its children, prefixing error messages with path
func (_dc *CT_SVGBlip )ValidateWithPath (path string )error {return nil };

// ValidateWithPath validates the SvgBlip and its children, prefixing error messages with path
func (_eb *SvgBlip )ValidateWithPath (path string )error {if _edf :=_eb .CT_SVGBlip .ValidateWithPath (path );_edf !=nil {return _edf ;};return nil ;};func NewSvgBlip ()*SvgBlip {_gf :=&SvgBlip {};_gf .CT_SVGBlip =*NewCT_SVGBlip ();return _gf };type SvgBlip struct{CT_SVGBlip };
func NewCT_SVGBlip ()*CT_SVGBlip {_ea :=&CT_SVGBlip {};return _ea };func (_a *CT_SVGBlip )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {if _a .EmbedAttr !=nil {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0065\u006d\u0062e\u0064"},Value :_b .Sprintf ("\u0025\u0076",*_a .EmbedAttr )});
};if _a .LinkAttr !=nil {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u006c\u0069\u006e\u006b"},Value :_b .Sprintf ("\u0025\u0076",*_a .LinkAttr )});};e .EncodeToken (start );e .EncodeToken (_d .EndElement {Name :start .Name });
return nil ;};type CT_SVGBlip struct{EmbedAttr *string ;LinkAttr *string ;};func (_fe *SvgBlip )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {_fe .CT_SVGBlip =*NewCT_SVGBlip ();for _ ,_ec :=range start .Attr {if _ec .Name .Space =="\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068\u0065\u006da\u0073\u002e\u006f\u0070\u0065\u006ex\u006d\u006c\u0066\u006f\u0072m\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u006f\u0066\u0066\u0069c\u0065\u0044\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002f\u0032\u0030\u0030\u0036\u002fr\u0065\u006c\u0061\u0074\u0069\u006f\u006e\u0073h\u0069\u0070\u0073"&&_ec .Name .Local =="\u0065\u006d\u0062e\u0064"{_cg :=_ec .Value ;
_fe .EmbedAttr =&_cg ;continue ;};if _ec .Name .Space =="\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068\u0065\u006da\u0073\u002e\u006f\u0070\u0065\u006ex\u006d\u006c\u0066\u006f\u0072m\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u006f\u0066\u0066\u0069c\u0065\u0044\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002f\u0032\u0030\u0030\u0036\u002fr\u0065\u006c\u0061\u0074\u0069\u006f\u006e\u0073h\u0069\u0070\u0073"&&_ec .Name .Local =="\u006c\u0069\u006e\u006b"{_gb :=_ec .Value ;
_fe .LinkAttr =&_gb ;continue ;};};for {_eg ,_gaa :=d .Token ();if _gaa !=nil {return _b .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0053\u0076\u0067\u0042\u006c\u0069\u0070\u003a\u0020\u0025\u0073",_gaa );};if _ffd ,_fd :=_eg .(_d .EndElement );
_fd &&_ffd .Name ==start .Name {break ;};};return nil ;};func init (){_e .RegisterConstructor ("\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069c\u0065\u002f\u0064\u0072\u0061w\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0053\u0056\u0047\u002f\u006d\u0061\u0069\u006e","\u0043\u0054\u005f\u0053\u0056\u0047\u0042\u006c\u0069\u0070",NewCT_SVGBlip );
_e .RegisterConstructor ("\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069c\u0065\u002f\u0064\u0072\u0061w\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0053\u0056\u0047\u002f\u006d\u0061\u0069\u006e","\u0073v\u0067\u0042\u006c\u0069\u0070",NewSvgBlip );
};