//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package diagram ;import (_a "encoding/xml";_d "fmt";_f "github.com/unidoc/unioffice/v2";_dg "github.com/unidoc/unioffice/v2/schema/soo/dml";);func (_cg *LstStyle )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_cg .CT_TextListStyle =*_dg .NewCT_TextListStyle ();
for {_e ,_dd :=d .Token ();if _dd !=nil {return _d .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u004c\u0073\u0074S\u0074\u0079\u006c\u0065: \u0025\u0073",_dd );};if _cd ,_de :=_e .(_a .EndElement );_de &&_cd .Name ==start .Name {break ;};};return nil ;
};

// Validate validates the SpPr and its children
func (_ge *SpPr )Validate ()error {return _ge .ValidateWithPath ("\u0053\u0070\u0050\u0072")};func NewLstStyle ()*LstStyle {_cc :=&LstStyle {};_cc .CT_TextListStyle =*_dg .NewCT_TextListStyle ();return _cc ;};

// Validate validates the LstStyle and its children
func (_g *LstStyle )Validate ()error {return _g .ValidateWithPath ("\u004c\u0073\u0074\u0053\u0074\u0079\u006c\u0065");};func (_ff *SpPr )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0031\u0032/\u0064\u0069\u0061\u0067\u0072a\u006d"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0073\u0070\u0050\u0072";return _ff .CT_ShapeProperties .MarshalXML (e ,start );};

// ValidateWithPath validates the SpPr and its children, prefixing error messages with path
func (_ca *SpPr )ValidateWithPath (path string )error {if _ffc :=_ca .CT_ShapeProperties .ValidateWithPath (path );_ffc !=nil {return _ffc ;};return nil ;};

// ValidateWithPath validates the LstStyle and its children, prefixing error messages with path
func (_dc *LstStyle )ValidateWithPath (path string )error {if _dge :=_dc .CT_TextListStyle .ValidateWithPath (path );_dge !=nil {return _dge ;};return nil ;};type SpPr struct{_dg .CT_ShapeProperties };func NewSpPr ()*SpPr {_cgb :=&SpPr {};_cgb .CT_ShapeProperties =*_dg .NewCT_ShapeProperties ();
return _cgb ;};func (_df *LstStyle )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0031\u0032/\u0064\u0069\u0061\u0067\u0072a\u006d"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u006c\u0073\u0074\u0053\u0074\u0079\u006c\u0065";return _df .CT_TextListStyle .MarshalXML (e ,start );};func (_gd *SpPr )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_gd .CT_ShapeProperties =*_dg .NewCT_ShapeProperties ();
for {_fb ,_da :=d .Token ();if _da !=nil {return _d .Errorf ("\u0070\u0061r\u0073\u0069\u006eg\u0020\u0053\u0070\u0050\u0072\u003a\u0020\u0025\u0073",_da );};if _b ,_fg :=_fb .(_a .EndElement );_fg &&_b .Name ==start .Name {break ;};};return nil ;};type LstStyle struct{_dg .CT_TextListStyle };
func init (){_f .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0031\u0032/\u0064\u0069\u0061\u0067\u0072a\u006d","\u0073\u0070\u0050\u0072",NewSpPr );
_f .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0031\u0032/\u0064\u0069\u0061\u0067\u0072a\u006d","\u006c\u0073\u0074\u0053\u0074\u0079\u006c\u0065",NewLstStyle );
};