//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

// Package diskstore implements tempStorage interface
// by using disk as a storage
package diskstore ;import (_gg "github.com/unidoc/unioffice/v2/common/tempstorage";_d "io/ioutil";_a "os";_g "strings";);

// Add is not applicable in the diskstore implementation
func (_eb diskStorage )Add (path string )error {return nil };

// RemoveAll removes all files in the directory
func (_bd diskStorage )RemoveAll (dir string )error {if _g .HasPrefix (dir ,_a .TempDir ()){return _a .RemoveAll (dir );};return nil ;};

// TempFile creates a new temp file by calling ioutil TempFile
func (_b diskStorage )TempFile (dir ,pattern string )(_gg .File ,error ){return _d .TempFile (dir ,pattern );};type diskStorage struct{};

// TempFile creates a new temp directory by calling ioutil TempDir
func (_de diskStorage )TempDir (pattern string )(string ,error ){return _d .TempDir ("",pattern )};

// Open opens file from disk according to a path
func (_e diskStorage )Open (path string )(_gg .File ,error ){return _a .OpenFile (path ,_a .O_RDWR ,0644)};

// SetAsStorage sets temp storage as a disk storage
func SetAsStorage (){_f :=diskStorage {};_gg .SetAsStorage (&_f )};