//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package wildcard ;func MatchSimple (pattern ,name string )bool {if pattern ==""{return name ==pattern ;};if pattern =="\u002a"{return true ;};_ba :=make ([]rune ,0,len (name ));_e :=make ([]rune ,0,len (pattern ));for _ ,_ef :=range name {_ba =append (_ba ,_ef );
};for _ ,_a :=range pattern {_e =append (_e ,_a );};_c :=true ;return _bab (_ba ,_e ,_c );};func _bb (_cb ,_cf []rune ,_ceg int )int {for len (_cf )> 0{switch _cf [0]{default:if len (_cb )==0{return -1;};if _cb [0]!=_cf [0]{return _bb (_cb [1:],_cf ,_ceg +1);
};case '?':if len (_cb )==0{return -1;};case '*':if len (_cb )==0{return -1;};_aeb :=_bb (_cb ,_cf [1:],_ceg );if _aeb !=-1{return _ceg ;}else {_aeb =_bb (_cb [1:],_cf ,_ceg );if _aeb !=-1{return _ceg ;}else {return -1;};};};_cb =_cb [1:];_cf =_cf [1:];
};return _ceg ;};func _bab (_gg ,_aec []rune ,_gb bool )bool {for len (_aec )> 0{switch _aec [0]{default:if len (_gg )==0||_gg [0]!=_aec [0]{return false ;};case '?':if len (_gg )==0&&!_gb {return false ;};case '*':return _bab (_gg ,_aec [1:],_gb )||(len (_gg )> 0&&_bab (_gg [1:],_aec ,_gb ));
};_gg =_gg [1:];_aec =_aec [1:];};return len (_gg )==0&&len (_aec )==0;};func Match (pattern ,name string )(_d bool ){if pattern ==""{return name ==pattern ;};if pattern =="\u002a"{return true ;};_ae :=make ([]rune ,0,len (name ));_ce :=make ([]rune ,0,len (pattern ));
for _ ,_cg :=range name {_ae =append (_ae ,_cg );};for _ ,_ca :=range pattern {_ce =append (_ce ,_ca );};_efe :=false ;return _bab (_ae ,_ce ,_efe );};func Index (pattern ,name string )(_ad int ){if pattern ==""||pattern =="\u002a"{return 0;};_fd :=make ([]rune ,0,len (name ));
_fa :=make ([]rune ,0,len (pattern ));for _ ,_df :=range name {_fd =append (_fd ,_df );};for _ ,_cef :=range pattern {_fa =append (_fa ,_cef );};return _bb (_fd ,_fa ,0);};