//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package rw ;import (_bf "bytes";_g "encoding/binary";_d "errors";_ee "fmt";_bb "io";_e "io/ioutil";_bfb "reflect";);func (_egae *Reader )ReadProperty (a interface{})error {_ce :=_bfb .ValueOf (a );for _ce .Kind ()==_bfb .Ptr {_ce =_ce .Elem ();};if !_ce .IsValid (){return _ee .Errorf ("\u0076a\u006cu\u0065\u0020\u0069\u0073\u0020n\u006f\u0074 \u0076\u0061\u006c\u0069\u0064");
};if _fb :=_egae .align (int (_ce .Type ().Size ()));_fb !=nil {return _fb ;};if _fbc :=_g .Read (_egae ,_g .LittleEndian ,a );_fbc !=nil {return _fbc ;};return nil ;};func PushLeftUI32 (v uint32 ,flag bool )uint32 {v >>=1;if flag {v |=1<<31;};return v ;
};func (_a *Reader )skip (_eg int )error {_ ,_c :=_bb .CopyN (_e .Discard ,_a ,int64 (_eg ));if _c !=nil {return _c ;};return nil ;};func (_dd *Writer )Cap ()int {return cap (_dd ._ccd )};func (_egc *Writer )tryGrowByReslice (_be int )(int ,bool ){if _baf :=len (_egc ._ccd );
_be <=cap (_egc ._ccd )-_baf {_egc ._ccd =_egc ._ccd [:_baf +_be ];return _baf ,true ;};return 0,false ;};func NewWriter ()*Writer {return &Writer {_ccd :[]byte {}}};func (_aa *Writer )WritePropertyNoAlign (a interface{})error {if _db :=_g .Write (_aa ,_g .LittleEndian ,a );
_db !=nil {return _db ;};return nil ;};func (_gcg *Writer )Write (p []byte )(_ab int ,_ef error ){_cfe ,_egf :=_gcg .tryGrowByReslice (len (p ));if !_egf {var _cag error ;_cfe ,_cag =_gcg .grow (len (p ));if _cag !=nil {return 0,_cag ;};};return copy (_gcg ._ccd [_cfe :],p ),nil ;
};const _bbd =64;func (_cf *Writer )WriteProperty (a interface{})error {if _cd :=_cf .align (int (_bfb .TypeOf (a ).Size ()));_cd !=nil {return _cd ;};return _cf .WritePropertyNoAlign (a );};func (_dcc *Writer )grow (_ede int )(int ,error ){_bee :=_dcc .Len ();
if _bee ==0&&_dcc ._bc !=0{_dcc .reset ();};if _fe ,_cg :=_dcc .tryGrowByReslice (_ede );_cg {return _fe ,nil ;};if _dcc ._ccd ==nil &&_ede <=_bbd {_dcc ._ccd =make ([]byte ,_ede ,_bbd );return 0,nil ;};_ag :=cap (_dcc ._ccd );if _ede <=_ag /2-_bee {copy (_dcc ._ccd ,_dcc ._ccd [_dcc ._bc :]);
}else if _ag > _gf -_ag -_ede {return 0,_ca ;}else {_cdf :=_fgc (2*_ag +_ede );copy (_cdf ,_dcc ._ccd [_dcc ._bc :]);_dcc ._ccd =_cdf ;};_dcc ._bc =0;_dcc ._ccd =_dcc ._ccd [:_bee +_ede ];return _bee ,nil ;};type Writer struct{_ccd []byte ;_bc int ;};var _ca =_d .New ("r\u0077.\u0057\u0072\u0069\u0074\u0065\u0072\u003a\u0020t\u006f\u006f\u0020\u006car\u0067\u0065");
func (_ceb *Writer )Skip (n int )error {if n ==0{return nil ;};_ ,_dca :=_ceb .Write (make ([]byte ,n ));return _dca ;};func (_bgd *Writer )Len ()int {return len (_bgd ._ccd )-_bgd ._bc };func PushLeftUI64 (v uint64 ,flag bool )uint64 {v >>=1;if flag {v |=1<<63;
};return v ;};func PopRightUI64 (v uint64 )(bool ,uint64 ){return (v &uint64 (1))==1,v >>1};func (_bfg *Writer )AlignLength (alignTo int )error {_edb :=_bfg .Len ()%alignTo ;if _edb > 0{_ ,_cfbg :=_bfg .Write (make ([]byte ,alignTo -_edb ));if _cfbg !=nil {return _cfbg ;
};};return nil ;};func (_bac *Writer )WriteByteAt (b byte ,off int )error {if off >=len (_bac ._ccd ){return _d .New ("\u004f\u0075\u0074\u0020\u006f\u0066\u0020\u0062\u006f\u0075\u006e\u0064\u0073");};_bac ._ccd [off ]=b ;return nil ;};type Reader struct{*_bf .Reader };
func (_fg *Writer )WriteStringProperty (s string )error {_fg .align (4);_cfb :=[]byte (s );if _df :=_g .Write (_fg ,_g .LittleEndian ,&_cfb );_df !=nil {return _df ;};return nil ;};func _fgc (_gfa int )[]byte {defer func (){if recover ()!=nil {panic (_ca );
};}();return make ([]byte ,_gfa );};func (_f *Reader )align (_ba int )error {return _f .skip ((_ba -_f .curPos ()%_ba )%_ba )};func (_eeg *Reader )curPos ()int {return int (_eeg .Size ())-_eeg .Len ()};func NewReader (b []byte )(*Reader ,error ){return &Reader {_bf .NewReader (b )},nil };
func (_da *Writer )curPos ()int {return int (_da .Cap ())-_da .Len ()};func (_dc *Reader )ReadPairProperty (p interface{})error {if _cc :=_dc .align (4);_cc !=nil {return _cc ;};_bg :=_bfb .ValueOf (p );for _bg .Kind ()==_bfb .Ptr {_bg =_bg .Elem ();};
if !_bg .IsValid (){return _ee .Errorf ("\u0076a\u006cu\u0065\u0020\u0069\u0073\u0020n\u006f\u0074 \u0076\u0061\u006c\u0069\u0064");};if _ea :=_g .Read (_dc ,_g .LittleEndian ,p );_ea !=nil {return _ea ;};return nil ;};func (_cbg *Writer )reset (){_cbg ._ccd =_cbg ._ccd [:0];
_cbg ._bc =0};func (_cdb *Writer )WriteTo (wTo _bb .Writer )(_ccf int64 ,_fbb error ){if _cb :=_cdb .Len ();_cb > 0{_fa ,_ga :=wTo .Write (_cdb ._ccd [_cdb ._bc :]);if _fa > _cb {return 0,_d .New ("\u0072\u0077\u002e\u0057\u0072\u0069\u0074\u0065\u0072\u002e\u0057\u0072\u0069\u0074\u0065\u0054\u006f\u003a\u0020\u0069\u006e\u0076\u0061\u006ci\u0064\u0020\u0057\u0072\u0069t\u0065\u0020c\u006f\u0075\u006e\u0074");
};_cdb ._bc +=_fa ;_ccf =int64 (_fa );if _ga !=nil {return _ccf ,_ga ;};if _fa !=_cb {return _ccf ,_bb .ErrShortWrite ;};};_cdb .reset ();return _ccf ,nil ;};func (_ac *Writer )Bytes ()[]byte {return _ac ._ccd };func (_gca *Writer )align (_cce int )error {return _gca .Skip ((_cce -(_gca .Len ())%_cce )%_cce )};
func PopRightUI32 (v uint32 )(bool ,uint32 ){return (v &uint32 (1))==1,v >>1};const _gf =int (^uint (0)>>1);func (_fef *Writer )FillWithByte (fillSize int ,b byte )error {for _cbc :=0;_cbc < fillSize ;_cbc ++{if _eed :=_fef .WritePropertyNoAlign (b );_eed !=nil {return _eed ;
};};return nil ;};func (_bfe *Reader )ReadStringProperty (n uint32 )(string ,error ){if _ed :=_bfe .align (4);_ed !=nil {return "",_ed ;};_egad :=make ([]byte ,n );if _gc :=_g .Read (_bfe ,_g .LittleEndian ,&_egad );_gc !=nil {return "",_gc ;};return string (_egad ),nil ;
};