//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package drawing ;import (_g "github.com/unidoc/unioffice/v2";_gf "github.com/unidoc/unioffice/v2/color";_c "github.com/unidoc/unioffice/v2/measurement";_a "github.com/unidoc/unioffice/v2/schema/soo/dml";);func (_fe ShapeProperties )LineProperties ()LineProperties {if _fe ._ae .Ln ==nil {_fe ._ae .Ln =_a .NewCT_LineProperties ();
};return LineProperties {_fe ._ae .Ln };};

// LineJoin is the type of line join
type LineJoin byte ;func (_eb ShapeProperties )SetSolidFill (c _gf .Color ){_eb .clearFill ();_eb ._ae .FillPropertiesChoice .SolidFill =_a .NewCT_SolidColorFillProperties ();_eb ._ae .FillPropertiesChoice .SolidFill .SrgbClr =_a .NewCT_SRgbColor ();_eb ._ae .FillPropertiesChoice .SolidFill .SrgbClr .ValAttr =*c .AsRGBString ();
};

// Properties returns the paragraph properties.
func (_aa Paragraph )Properties ()ParagraphProperties {if _aa ._dd .PPr ==nil {_aa ._dd .PPr =_a .NewCT_TextParagraphProperties ();};return MakeParagraphProperties (_aa ._dd .PPr );};

// SetAlign controls the paragraph alignment
func (_ge ParagraphProperties )SetAlign (a _a .ST_TextAlignType ){_ge ._cb .AlgnAttr =a };

// SetWidth sets the line width, MS products treat zero as the minimum width
// that can be displayed.
func (_de LineProperties )SetWidth (w _c .Distance ){_de ._dc .WAttr =_g .Int32 (int32 (w /_c .EMU ))};func (_fab ShapeProperties )SetNoFill (){_fab .clearFill ();_fab ._ae .FillPropertiesChoice .NoFill =_a .NewCT_NoFillProperties ();};func (_b LineProperties )SetSolidFill (c _gf .Color ){_b .clearFill ();
_b ._dc .LineFillPropertiesChoice .SolidFill =_a .NewCT_SolidColorFillProperties ();_b ._dc .LineFillPropertiesChoice .SolidFill .SrgbClr =_a .NewCT_SRgbColor ();_b ._dc .LineFillPropertiesChoice .SolidFill .SrgbClr .ValAttr =*c .AsRGBString ();};func (_ef LineProperties )clearFill (){_ef ._dc .LineFillPropertiesChoice =_a .NewEG_LineFillPropertiesChoice ();
};

// SetNumbered controls if bullets are numbered or not.
func (_ed ParagraphProperties )SetNumbered (scheme _a .ST_TextAutonumberScheme ){if scheme ==_a .ST_TextAutonumberSchemeUnset {_ed ._cb .TextBulletChoice .BuAutoNum =nil ;}else {_ed ._cb .TextBulletChoice .BuAutoNum =_a .NewCT_TextAutonumberBullet ();_ed ._cb .TextBulletChoice .BuAutoNum .TypeAttr =scheme ;
};};

// ParagraphProperties allows controlling paragraph properties.
type ParagraphProperties struct{_cb *_a .CT_TextParagraphProperties ;};

// Properties returns the run's properties.
func (_efc Run )Properties ()RunProperties {if _efc ._gef .TextRunChoice .R ==nil {_efc ._gef .TextRunChoice .R =_a .NewCT_RegularTextRun ();};if _efc ._gef .TextRunChoice .R .RPr ==nil {_efc ._gef .TextRunChoice .R .RPr =_a .NewCT_TextCharacterProperties ();
};return RunProperties {_efc ._gef .TextRunChoice .R .RPr };};

// GetPosition gets the position of the shape in EMU.
func (_aea ShapeProperties )GetPosition ()(int64 ,int64 ){_aea .ensureXfrm ();if _aea ._ae .Xfrm .Off ==nil {_aea ._ae .Xfrm .Off =_a .NewCT_Point2D ();};return *_aea ._ae .Xfrm .Off .XAttr .ST_CoordinateUnqualified ,*_aea ._ae .Xfrm .Off .YAttr .ST_CoordinateUnqualified ;
};

// X returns the inner wrapped XML type.
func (_e LineProperties )X ()*_a .CT_LineProperties {return _e ._dc };

// X returns the inner wrapped XML type.
func (_gga ParagraphProperties )X ()*_a .CT_TextParagraphProperties {return _gga ._cb };

// SetBold controls the bolding of a run.
func (_af RunProperties )SetBold (b bool ){_af ._dca .BAttr =_g .Bool (b )};

// Run is a run within a paragraph.
type Run struct{_gef *_a .EG_TextRun };

// X returns the inner wrapped XML type.
func (_dg Paragraph )X ()*_a .CT_TextParagraph {return _dg ._dd };

// X returns the inner wrapped XML type.
func (_dab Run )X ()*_a .EG_TextRun {return _dab ._gef };

// SetBulletFont controls the font for the bullet character.
func (_ac ParagraphProperties )SetBulletFont (f string ){if f ==""{_ac ._cb .TextBulletTypefaceChoice .BuFont =nil ;}else {_ac ._cb .TextBulletTypefaceChoice .BuFont =_a .NewCT_TextFont ();_ac ._cb .TextBulletTypefaceChoice .BuFont .TypefaceAttr =f ;};
};

// SetPosition sets the position of the shape.
func (_abb ShapeProperties )SetPosition (x ,y _c .Distance ){_abb .ensureXfrm ();if _abb ._ae .Xfrm .Off ==nil {_abb ._ae .Xfrm .Off =_a .NewCT_Point2D ();};_abb ._ae .Xfrm .Off .XAttr .ST_CoordinateUnqualified =_g .Int64 (int64 (x /_c .EMU ));_abb ._ae .Xfrm .Off .YAttr .ST_CoordinateUnqualified =_g .Int64 (int64 (y /_c .EMU ));
};

// SetText sets the run's text contents.
func (_efe Run )SetText (s string ){_efe ._gef .TextRunChoice .Br =nil ;_efe ._gef .TextRunChoice .Fld =nil ;if _efe ._gef .TextRunChoice .R ==nil {_efe ._gef .TextRunChoice .R =_a .NewCT_RegularTextRun ();};_efe ._gef .TextRunChoice .R .T =s ;};const (LineJoinRound LineJoin =iota ;
LineJoinBevel ;LineJoinMiter ;);

// SetFont controls the font of a run.
func (_fa RunProperties )SetFont (s string ){_fa ._dca .Latin =_a .NewCT_TextFont ();_fa ._dca .Latin .TypefaceAttr =s ;};

// SetJoin sets the line join style.
func (_gfc LineProperties )SetJoin (e LineJoin ){_gfc ._dc .LineJoinPropertiesChoice =_a .NewEG_LineJoinPropertiesChoice ();switch e {case LineJoinRound :_gfc ._dc .LineJoinPropertiesChoice .Round =_a .NewCT_LineJoinRound ();case LineJoinBevel :_gfc ._dc .LineJoinPropertiesChoice .Bevel =_a .NewCT_LineJoinBevel ();
case LineJoinMiter :_gfc ._dc .LineJoinPropertiesChoice .Miter =_a .NewCT_LineJoinMiterProperties ();};};type ShapeProperties struct{_ae *_a .CT_ShapeProperties };func (_ce ShapeProperties )clearFill (){_ce ._ae .FillPropertiesChoice =_a .NewEG_FillPropertiesChoice ();
};

// Paragraph is a paragraph within a document.
type Paragraph struct{_dd *_a .CT_TextParagraph };

// AddRun adds a new run to a paragraph.
func (_ee Paragraph )AddRun ()Run {_def :=MakeRun (_a .NewEG_TextRun ());_ee ._dd .EG_TextRun =append (_ee ._dd .EG_TextRun ,_def .X ());return _def ;};

// SetGeometry sets the shape type of the shape
func (_df ShapeProperties )SetGeometry (g _a .ST_ShapeType ){if _df ._ae .GeometryChoice .PrstGeom ==nil {_df ._ae .GeometryChoice .PrstGeom =_a .NewCT_PresetGeometry2D ();};_df ._ae .GeometryChoice .PrstGeom .PrstAttr =g ;};

// MakeRunProperties constructs a new RunProperties wrapper.
func MakeRunProperties (x *_a .CT_TextCharacterProperties )RunProperties {return RunProperties {x }};

// SetSize sets the font size of the run text
func (_acg RunProperties )SetSize (sz _c .Distance ){_acg ._dca .SzAttr =_g .Int32 (int32 (sz /_c .HundredthPoint ));};

// SetSize sets the width and height of the shape.
func (_fef ShapeProperties )SetSize (w ,h _c .Distance ){_fef .SetWidth (w );_fef .SetHeight (h )};

// SetFlipVertical controls if the shape is flipped vertically.
func (_cc ShapeProperties )SetFlipVertical (b bool ){_cc .ensureXfrm ();if !b {_cc ._ae .Xfrm .FlipVAttr =nil ;}else {_cc ._ae .Xfrm .FlipVAttr =_g .Bool (true );};};func (_cf ShapeProperties )ensureXfrm (){if _cf ._ae .Xfrm ==nil {_cf ._ae .Xfrm =_a .NewCT_Transform2D ();
};};func MakeShapeProperties (x *_a .CT_ShapeProperties )ShapeProperties {return ShapeProperties {x }};

// SetSolidFill controls the text color of a run.
func (_efd RunProperties )SetSolidFill (c _gf .Color ){_efd ._dca .FillPropertiesChoice =_a .NewEG_FillPropertiesChoice ();_efd ._dca .FillPropertiesChoice .SolidFill =_a .NewCT_SolidColorFillProperties ();_efd ._dca .FillPropertiesChoice .SolidFill .SrgbClr =_a .NewCT_SRgbColor ();
_efd ._dca .FillPropertiesChoice .SolidFill .SrgbClr .ValAttr =*c .AsRGBString ();};func (_ab LineProperties )SetNoFill (){_ab .clearFill ();_ab ._dc .LineFillPropertiesChoice .NoFill =_a .NewCT_NoFillProperties ();};

// SetHeight sets the height of the shape.
func (_ea ShapeProperties )SetHeight (h _c .Distance ){_ea .ensureXfrm ();if _ea ._ae .Xfrm .Ext ==nil {_ea ._ae .Xfrm .Ext =_a .NewCT_PositiveSize2D ();};_ea ._ae .Xfrm .Ext .CyAttr =int64 (h /_c .EMU );};

// MakeParagraph constructs a new paragraph wrapper.
func MakeParagraph (x *_a .CT_TextParagraph )Paragraph {return Paragraph {x }};

// MakeParagraphProperties constructs a new ParagraphProperties wrapper.
func MakeParagraphProperties (x *_a .CT_TextParagraphProperties )ParagraphProperties {return ParagraphProperties {x };};

// MakeRun constructs a new Run wrapper.
func MakeRun (x *_a .EG_TextRun )Run {return Run {x }};

// X returns the inner wrapped XML type.
func (_dee ShapeProperties )X ()*_a .CT_ShapeProperties {return _dee ._ae };

// AddBreak adds a new line break to a paragraph.
func (_efg Paragraph )AddBreak (){_gg :=_a .NewEG_TextRun ();_gg .TextRunChoice .Br =_a .NewCT_TextLineBreak ();_efg ._dd .EG_TextRun =append (_efg ._dd .EG_TextRun ,_gg );};

// SetLevel sets the level of indentation of a paragraph.
func (_f ParagraphProperties )SetLevel (idx int32 ){_f ._cb .LvlAttr =_g .Int32 (idx )};

// SetWidth sets the width of the shape.
func (_bd ShapeProperties )SetWidth (w _c .Distance ){_bd .ensureXfrm ();if _bd ._ae .Xfrm .Ext ==nil {_bd ._ae .Xfrm .Ext =_a .NewCT_PositiveSize2D ();};_bd ._ae .Xfrm .Ext .CxAttr =int64 (w /_c .EMU );};

// SetBulletChar sets the bullet character for the paragraph.
func (_da ParagraphProperties )SetBulletChar (c string ){if c ==""{_da ._cb .TextBulletChoice .BuChar =nil ;}else {_da ._cb .TextBulletChoice .BuChar =_a .NewCT_TextCharBullet ();_da ._cb .TextBulletChoice .BuChar .CharAttr =c ;};};

// RunProperties controls the run properties.
type RunProperties struct{_dca *_a .CT_TextCharacterProperties ;};type LineProperties struct{_dc *_a .CT_LineProperties };

// SetFlipHorizontal controls if the shape is flipped horizontally.
func (_dfc ShapeProperties )SetFlipHorizontal (b bool ){_dfc .ensureXfrm ();if !b {_dfc ._ae .Xfrm .FlipHAttr =nil ;}else {_dfc ._ae .Xfrm .FlipHAttr =_g .Bool (true );};};