//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package oembed ;import (_b "encoding/xml";_fa "fmt";_e "github.com/unidoc/unioffice/v2";_g "strconv";);func _gg (_a bool )uint8 {if _a {return 1;};return 0;};type Oembed struct{CT_OEmbed };

// ValidateWithPath validates the CT_OEmbed and its children, prefixing error messages with path
func (_ef *CT_OEmbed )ValidateWithPath (path string )error {return nil };func (_c *CT_OEmbed )UnmarshalXML (d *_b .Decoder ,start _b .StartElement )error {for _ ,_cf :=range start .Attr {if _cf .Name .Local =="\u006fE\u006d\u0062\u0065\u0064\u0055\u0072l"{_d :=_cf .Value ;
_c .OEmbedUrlAttr =_d ;continue ;};if _cf .Name .Local =="\u006de\u0064\u0069\u0061\u0054\u0079\u0070e"{_ga :=_cf .Value ;_c .MediaTypeAttr =_ga ;continue ;};if _cf .Name .Local =="p\u0069\u0063\u004c\u006fck\u0073A\u0075\u0074\u006f\u0046\u006fr\u004f\u0045\u006d\u0062\u0065\u0064"{_bc ,_gf :=_g .ParseBool (_cf .Value );
if _gf !=nil {return _gf ;};_c .PicLocksAutoForOEmbedAttr =&_bc ;continue ;};};for {_gd ,_dd :=d .Token ();if _dd !=nil {return _fa .Errorf ("p\u0061\u0072\u0073\u0069ng\u0020C\u0054\u005f\u004f\u0045\u006db\u0065\u0064\u003a\u0020\u0025\u0073",_dd );};
if _da ,_dad :=_gd .(_b .EndElement );_dad &&_da .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the Oembed and its children, prefixing error messages with path
func (_ca *Oembed )ValidateWithPath (path string )error {if _de :=_ca .CT_OEmbed .ValidateWithPath (path );_de !=nil {return _de ;};return nil ;};

// Validate validates the Oembed and its children
func (_eg *Oembed )Validate ()error {return _eg .ValidateWithPath ("\u004f\u0065\u006d\u0062\u0065\u0064");};func NewCT_OEmbed ()*CT_OEmbed {_bf :=&CT_OEmbed {};return _bf };func (_dda *Oembed )UnmarshalXML (d *_b .Decoder ,start _b .StartElement )error {_dda .CT_OEmbed =*NewCT_OEmbed ();
for _ ,_ee :=range start .Attr {if _ee .Name .Local =="\u006fE\u006d\u0062\u0065\u0064\u0055\u0072l"{_fc :=_ee .Value ;_dda .OEmbedUrlAttr =_fc ;continue ;};if _ee .Name .Local =="\u006de\u0064\u0069\u0061\u0054\u0079\u0070e"{_ce :=_ee .Value ;_dda .MediaTypeAttr =_ce ;
continue ;};if _ee .Name .Local =="p\u0069\u0063\u004c\u006fck\u0073A\u0075\u0074\u006f\u0046\u006fr\u004f\u0045\u006d\u0062\u0065\u0064"{_fb ,_gfc :=_g .ParseBool (_ee .Value );if _gfc !=nil {return _gfc ;};_dda .PicLocksAutoForOEmbedAttr =&_fb ;continue ;
};};for {_gdg ,_dae :=d .Token ();if _dae !=nil {return _fa .Errorf ("\u0070a\u0072s\u0069\u006e\u0067\u0020\u004fe\u006d\u0062e\u0064\u003a\u0020\u0025\u0073",_dae );};if _cg ,_be :=_gdg .(_b .EndElement );_be &&_cg .Name ==start .Name {break ;};};return nil ;
};func (_gc *Oembed )MarshalXML (e *_b .Encoder ,start _b .StartElement )error {start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0032\u0030\u002f\u006f\u0065\u006d\u0062\u0065\u0064"});
start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u006f\u0065\u006d\u0062\u0065\u0064";return _gc .CT_OEmbed .MarshalXML (e ,start );};type CT_OEmbed struct{OEmbedUrlAttr string ;MediaTypeAttr string ;PicLocksAutoForOEmbedAttr *bool ;};func (_gb *CT_OEmbed )MarshalXML (e *_b .Encoder ,start _b .StartElement )error {start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u006fE\u006d\u0062\u0065\u0064\u0055\u0072l"},Value :_fa .Sprintf ("\u0025\u0076",_gb .OEmbedUrlAttr )});
start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u006de\u0064\u0069\u0061\u0054\u0079\u0070e"},Value :_fa .Sprintf ("\u0025\u0076",_gb .MediaTypeAttr )});if _gb .PicLocksAutoForOEmbedAttr !=nil {start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"p\u0069\u0063\u004c\u006fck\u0073A\u0075\u0074\u006f\u0046\u006fr\u004f\u0045\u006d\u0062\u0065\u0064"},Value :_fa .Sprintf ("\u0025\u0064",_gg (*_gb .PicLocksAutoForOEmbedAttr ))});
};e .EncodeToken (start );e .EncodeToken (_b .EndElement {Name :start .Name });return nil ;};

// Validate validates the CT_OEmbed and its children
func (_eb *CT_OEmbed )Validate ()error {return _eb .ValidateWithPath ("\u0043T\u005f\u004f\u0045\u006d\u0062\u0065d");};func NewOembed ()*Oembed {_fag :=&Oembed {};_fag .CT_OEmbed =*NewCT_OEmbed ();return _fag };func init (){_e .RegisterConstructor ("\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0032\u0030\u002f\u006f\u0065\u006d\u0062\u0065\u0064","\u0043T\u005f\u004f\u0045\u006d\u0062\u0065d",NewCT_OEmbed );
_e .RegisterConstructor ("\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0032\u0030\u002f\u006f\u0065\u006d\u0062\u0065\u0064","\u006f\u0065\u006d\u0062\u0065\u0064",NewOembed );
};