//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package diagram ;import (_a "encoding/xml";_c "fmt";_fe "github.com/unidoc/unioffice/v2";_d "github.com/unidoc/unioffice/v2/schema/soo/dml";_f "strconv";);type RecolorImg struct{CT_Boolean };

// ValidateWithPath validates the CT_Boolean and its children, prefixing error messages with path
func (_acf *CT_Boolean )ValidateWithPath (path string )error {return nil };

// Validate validates the CNvPr and its children
func (_fb *CNvPr )Validate ()error {return _fb .ValidateWithPath ("\u0043\u004e\u0076P\u0072")};func NewCT_Boolean ()*CT_Boolean {_bc :=&CT_Boolean {};return _bc };func (_gc *CT_Boolean )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {if _gc .ValAttr !=nil {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0076\u0061\u006c"},Value :_c .Sprintf ("\u0025\u0064",_cec (*_gc .ValAttr ))});
};e .EncodeToken (start );e .EncodeToken (_a .EndElement {Name :start .Name });return nil ;};func NewRecolorImg ()*RecolorImg {_aeb :=&RecolorImg {};_aeb .CT_Boolean =*NewCT_Boolean ();return _aeb ;};type CNvPr struct{_d .CT_NonVisualDrawingProps };func (_ee *CT_Boolean )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {for _ ,_gga :=range start .Attr {if _gga .Name .Local =="\u0076\u0061\u006c"{_fc ,_cd :=_f .ParseBool (_gga .Value );
if _cd !=nil {return _cd ;};_ee .ValAttr =&_fc ;continue ;};};for {_ab ,_bcc :=d .Token ();if _bcc !=nil {return _c .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0043\u0054\u005f\u0042\u006f\u006f\u006c\u0065\u0061\u006e\u003a\u0020%\u0073",_bcc );
};if _fg ,_ae :=_ab .(_a .EndElement );_ae &&_fg .Name ==start .Name {break ;};};return nil ;};type CT_Boolean struct{ValAttr *bool ;};

// Validate validates the CT_Boolean and its children
func (_fd *CT_Boolean )Validate ()error {return _fd .ValidateWithPath ("\u0043\u0054\u005f\u0042\u006f\u006f\u006c\u0065\u0061\u006e");};func NewCNvPr ()*CNvPr {_e :=&CNvPr {};_e .CT_NonVisualDrawingProps =*_d .NewCT_NonVisualDrawingProps ();return _e ;
};

// Validate validates the RecolorImg and its children
func (_ce *RecolorImg )Validate ()error {return _ce .ValidateWithPath ("\u0052\u0065\u0063\u006f\u006c\u006f\u0072\u0049\u006d\u0067");};func (_acb *RecolorImg )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0072\u0065\u0063\u006f\u006c\u006f\u0072\u0049\u006d\u0067";return _acb .CT_Boolean .MarshalXML (e ,start );};func _cec (_dg bool )uint8 {if _dg {return 1;};return 0;};

// ValidateWithPath validates the RecolorImg and its children, prefixing error messages with path
func (_dfc *RecolorImg )ValidateWithPath (path string )error {if _fgea :=_dfc .CT_Boolean .ValidateWithPath (path );_fgea !=nil {return _fgea ;};return nil ;};

// ValidateWithPath validates the CNvPr and its children, prefixing error messages with path
func (_gf *CNvPr )ValidateWithPath (path string )error {if _gg :=_gf .CT_NonVisualDrawingProps .ValidateWithPath (path );_gg !=nil {return _gg ;};return nil ;};func (_df *CNvPr )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0063\u004e\u0076P\u0072";return _df .CT_NonVisualDrawingProps .MarshalXML (e ,start );};func (_db *CNvPr )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_db .CT_NonVisualDrawingProps =*_d .NewCT_NonVisualDrawingProps ();
for {_bg ,_ac :=d .Token ();if _ac !=nil {return _c .Errorf ("\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0043\u004e\u0076\u0050r\u003a\u0020\u0025\u0073",_ac );};if _g ,_fa :=_bg .(_a .EndElement );_fa &&_g .Name ==start .Name {break ;};};return nil ;
};func (_bccd *RecolorImg )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_bccd .CT_Boolean =*NewCT_Boolean ();for _ ,_dcb :=range start .Attr {if _dcb .Name .Local =="\u0076\u0061\u006c"{_bcd ,_ca :=_f .ParseBool (_dcb .Value );if _ca !=nil {return _ca ;
};_bccd .ValAttr =&_bcd ;continue ;};};for {_fge ,_eg :=d .Token ();if _eg !=nil {return _c .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0052\u0065\u0063\u006f\u006c\u006f\u0072\u0049\u006d\u0067\u003a\u0020%\u0073",_eg );};if _de ,_gd :=_fge .(_a .EndElement );
_gd &&_de .Name ==start .Name {break ;};};return nil ;};func init (){_fe .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d","\u0043\u0054\u005f\u0042\u006f\u006f\u006c\u0065\u0061\u006e",NewCT_Boolean );
_fe .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d","\u0063\u004e\u0076P\u0072",NewCNvPr );
_fe .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d","\u0072\u0065\u0063\u006f\u006c\u006f\u0072\u0049\u006d\u0067",NewRecolorImg );
};