//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package imageformula ;import (_g "encoding/xml";_ae "fmt";_c "github.com/unidoc/unioffice/v2";);

// Validate validates the ImageFormula and its children
func (_ge *ImageFormula )Validate ()error {return _ge .ValidateWithPath ("\u0049\u006d\u0061g\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061");};

// ValidateWithPath validates the CT_ImageFormula and its children, prefixing error messages with path
func (_cbb *CT_ImageFormula )ValidateWithPath (path string )error {return nil };func NewImageFormula ()*ImageFormula {_eg :=&ImageFormula {};_eg .CT_ImageFormula =*NewCT_ImageFormula ();return _eg ;};func (_e *CT_ImageFormula )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {for _ ,_gg :=range start .Attr {if _gg .Name .Local =="\u0066o\u0072\u006d\u0075\u006c\u0061"{_gf :=_gg .Value ;
_e .FormulaAttr =&_gf ;continue ;};};for {_b ,_bd :=d .Token ();if _bd !=nil {return _ae .Errorf ("p\u0061\u0072\u0073\u0069\u006e\u0067 \u0043\u0054\u005f\u0049\u006d\u0061\u0067\u0065\u0046o\u0072\u006d\u0075l\u0061:\u0020\u0025\u0073",_bd );};if _f ,_df :=_b .(_g .EndElement );
_df &&_f .Name ==start .Name {break ;};};return nil ;};type ImageFormula struct{CT_ImageFormula };type CT_ImageFormula struct{FormulaAttr *string ;};

// Validate validates the CT_ImageFormula and its children
func (_gd *CT_ImageFormula )Validate ()error {return _gd .ValidateWithPath ("\u0043T\u005fI\u006d\u0061\u0067\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061");};

// ValidateWithPath validates the ImageFormula and its children, prefixing error messages with path
func (_fb *ImageFormula )ValidateWithPath (path string )error {if _fcg :=_fb .CT_ImageFormula .ValidateWithPath (path );_fcg !=nil {return _fcg ;};return nil ;};func (_fd *ImageFormula )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {_fd .CT_ImageFormula =*NewCT_ImageFormula ();
for _ ,_be :=range start .Attr {if _be .Name .Local =="\u0066o\u0072\u006d\u0075\u006c\u0061"{_ab :=_be .Value ;_fd .FormulaAttr =&_ab ;continue ;};};for {_fda ,_ba :=d .Token ();if _ba !=nil {return _ae .Errorf ("\u0070a\u0072\u0073\u0069\u006e\u0067\u0020\u0049\u006d\u0061\u0067\u0065F\u006f\u0072\u006d\u0075\u006c\u0061\u003a\u0020\u0025\u0073",_ba );
};if _cd ,_fc :=_fda .(_g .EndElement );_fc &&_cd .Name ==start .Name {break ;};};return nil ;};func (_aa *CT_ImageFormula )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {if _aa .FormulaAttr !=nil {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0066o\u0072\u006d\u0075\u006c\u0061"},Value :_ae .Sprintf ("\u0025\u0076",*_aa .FormulaAttr )});
};e .EncodeToken (start );e .EncodeToken (_g .EndElement {Name :start .Name });return nil ;};func (_ee *ImageFormula )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"h\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006fm\u002fo\u0066\u0066\u0069\u0063e\u002f\u0064r\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0032\u002f\u0069\u006d\u0061\u0067\u0065\u0066\u006f\u0072\u006d\u0075\u006c\u0061"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0069\u006d\u0061g\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061";return _ee .CT_ImageFormula .MarshalXML (e ,start );};func NewCT_ImageFormula ()*CT_ImageFormula {_cb :=&CT_ImageFormula {};return _cb };func init (){_c .RegisterConstructor ("h\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006fm\u002fo\u0066\u0066\u0069\u0063e\u002f\u0064r\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0032\u002f\u0069\u006d\u0061\u0067\u0065\u0066\u006f\u0072\u006d\u0075\u006c\u0061","\u0043T\u005fI\u006d\u0061\u0067\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061",NewCT_ImageFormula );
_c .RegisterConstructor ("h\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006fm\u002fo\u0066\u0066\u0069\u0063e\u002f\u0064r\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0032\u002f\u0069\u006d\u0061\u0067\u0065\u0066\u006f\u0072\u006d\u0075\u006c\u0061","\u0069\u006d\u0061g\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061",NewImageFormula );
};