//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package cid ;import (_dd "encoding/xml";_a "fmt";_ag "github.com/unidoc/unioffice/v2";_ad "github.com/unidoc/unioffice/v2/common/logger";_g "strconv";);func (_eb *CT_CommentsIds )MarshalXML (e *_dd .Encoder ,start _dd .StartElement )error {e .EncodeToken (start );
if _eb .CommentId !=nil {_gda :=_dd .StartElement {Name :_dd .Name {Local :"\u0063\u0069\u0064\u003a\u0063\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064"}};for _ ,_dg :=range _eb .CommentId {e .EncodeElement (_dg ,_gda );};};e .EncodeToken (_dd .EndElement {Name :start .Name });
return nil ;};func NewCT_CommentsIds ()*CT_CommentsIds {_bb :=&CT_CommentsIds {};return _bb };

// ValidateWithPath validates the DecimaldurableId and its children, prefixing error messages with path
func (_ed *DecimaldurableId )ValidateWithPath (path string )error {return nil };

// Validate validates the CT_CommentsIds and its children
func (_bac *CT_CommentsIds )Validate ()error {return _bac .ValidateWithPath ("\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073");};func NewCommentsIds ()*CommentsIds {_de :=&CommentsIds {};_de .CT_CommentsIds =*NewCT_CommentsIds ();
return _de ;};

// Validate validates the DecimaldurableId and its children
func (_bfe *DecimaldurableId )Validate ()error {return _bfe .ValidateWithPath ("\u0044\u0065c\u0069\u006d\u0061l\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064");};type CT_CommentId struct{ParaIdAttr string ;DurableIdAttr string ;};func (_gb *CT_CommentsIds )UnmarshalXML (d *_dd .Decoder ,start _dd .StartElement )error {_bc :for {_eag ,_ce :=d .Token ();
if _ce !=nil {return _ce ;};switch _eagb :=_eag .(type ){case _dd .StartElement :switch _eagb .Name {case _dd .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064",Local :"\u0063o\u006d\u006d\u0065\u006e\u0074\u0049d"}:_dab :=NewCT_CommentId ();
if _bef :=d .DecodeElement (_dab ,&_eagb );_bef !=nil {return _bef ;};_gb .CommentId =append (_gb .CommentId ,_dab );default:_ad .Log .Debug ("\u0073\u006b\u0069\u0070\u0070\u0069n\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065\u0064\u0020\u0065\u006c\u0065\u006d\u0065\u006et\u0020\u006f\u006e\u0020\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006e\u0074s\u0049d\u0073\u0020\u0025\u0076",_eagb .Name );
if _gbe :=d .Skip ();_gbe !=nil {return _gbe ;};};case _dd .EndElement :break _bc ;case _dd .CharData :};};return nil ;};type CommentsIds struct{CT_CommentsIds };func (_eab *DecimaldurableId )UnmarshalXML (d *_dd .Decoder ,start _dd .StartElement )error {for _ ,_cad :=range start .Attr {if _cad .Name .Local =="\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"{_cbg ,_dee :=_g .ParseInt (_cad .Value ,10,64);
if _dee !=nil {return _dee ;};_eab .DurableIdAttr =&_cbg ;continue ;};};for {_bacg ,_bg :=d .Token ();if _bg !=nil {return _a .Errorf ("\u0070\u0061\u0072\u0073i\u006e\u0067\u0020\u0044\u0065\u0063\u0069\u006d\u0061\u006cd\u0075r\u0061\u0062\u006c\u0065\u0049\u0064\u003a \u0025\u0073",_bg );
};if _fc ,_ac :=_bacg .(_dd .EndElement );_ac &&_fc .Name ==start .Name {break ;};};return nil ;};func NewCT_CommentId ()*CT_CommentId {_b :=&CT_CommentId {};return _b };type DecimaldurableId struct{DurableIdAttr *int64 ;};

// ValidateWithPath validates the CT_CommentId and its children, prefixing error messages with path
func (_dae *CT_CommentId )ValidateWithPath (path string )error {return nil };

// Validate validates the CT_CommentId and its children
func (_e *CT_CommentId )Validate ()error {return _e .ValidateWithPath ("\u0043\u0054\u005fC\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064");};func (_ee *DecimaldurableId )MarshalXML (e *_dd .Encoder ,start _dd .StartElement )error {if _ee .DurableIdAttr !=nil {start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"},Value :_a .Sprintf ("\u0025\u0076",*_ee .DurableIdAttr )});
};start .Name .Local ="c\u0069d\u003a\u0064\u0065\u0063\u0069\u006d\u0061\u006cd\u0075\u0072\u0061\u0062le\u0049\u0064";return nil ;};

// Validate validates the CommentsIds and its children
func (_bf *CommentsIds )Validate ()error {return _bf .ValidateWithPath ("C\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073");};func NewDecimaldurableId ()*DecimaldurableId {_cg :=&DecimaldurableId {};return _cg };

// ValidateWithPath validates the CT_CommentsIds and its children, prefixing error messages with path
func (_ae *CT_CommentsIds )ValidateWithPath (path string )error {for _ab ,_gf :=range _ae .CommentId {if _aa :=_gf .ValidateWithPath (_a .Sprintf ("\u0025\u0073/\u0043\u006f\u006dm\u0065\u006e\u0074\u0049\u0064\u005b\u0025\u0064\u005d",path ,_ab ));_aa !=nil {return _aa ;
};};return nil ;};func (_agf *CommentsIds )UnmarshalXML (d *_dd .Decoder ,start _dd .StartElement )error {_agf .CT_CommentsIds =*NewCT_CommentsIds ();_aeg :for {_cb ,_gbg :=d .Token ();if _gbg !=nil {return _gbg ;};switch _beb :=_cb .(type ){case _dd .StartElement :switch _beb .Name {case _dd .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064",Local :"\u0063o\u006d\u006d\u0065\u006e\u0074\u0049d"}:_ebd :=NewCT_CommentId ();
if _ef :=d .DecodeElement (_ebd ,&_beb );_ef !=nil {return _ef ;};_agf .CommentId =append (_agf .CommentId ,_ebd );default:_ad .Log .Debug ("\u0073\u006bi\u0070\u0070\u0069\u006e\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065\u0064\u0020\u0065\u006c\u0065\u006d\u0065\u006e\u0074\u0020\u006f\u006e\u0020\u0043\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073\u0020\u0025\u0076",_beb .Name );
if _ca :=d .Skip ();_ca !=nil {return _ca ;};};case _dd .EndElement :break _aeg ;case _dd .CharData :};};return nil ;};func (_f *CT_CommentId )UnmarshalXML (d *_dd .Decoder ,start _dd .StartElement )error {for _ ,_fd :=range start .Attr {if _fd .Name .Local =="\u0070\u0061\u0072\u0061\u0049\u0064"{_ba :=_fd .Value ;
_f .ParaIdAttr =_ba ;continue ;};if _fd .Name .Local =="\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"{_ga :=_fd .Value ;_f .DurableIdAttr =_ga ;continue ;};};for {_gc ,_da :=d .Token ();if _da !=nil {return _a .Errorf ("\u0070a\u0072\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005f\u0043\u006fm\u006d\u0065\u006e\u0074\u0049\u0064\u003a\u0020\u0025\u0073",_da );
};if _gd ,_c :=_gc .(_dd .EndElement );_c &&_gd .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the CommentsIds and its children, prefixing error messages with path
func (_gce *CommentsIds )ValidateWithPath (path string )error {if _bebd :=_gce .CT_CommentsIds .ValidateWithPath (path );_bebd !=nil {return _bebd ;};return nil ;};func (_dcg *CommentsIds )MarshalXML (e *_dd .Encoder ,start _dd .StartElement )error {start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064"});
start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0063\u0069d"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064"});
start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0063i\u0064:\u0063\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073";return _dcg .CT_CommentsIds .MarshalXML (e ,start );};type CT_CommentsIds struct{CommentId []*CT_CommentId ;};func (_dc *CT_CommentId )MarshalXML (e *_dd .Encoder ,start _dd .StartElement )error {start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0063\u0069\u0064\u003a\u0070\u0061\u0072\u0061\u0049\u0064"},Value :_a .Sprintf ("\u0025\u0076",_dc .ParaIdAttr )});
start .Attr =append (start .Attr ,_dd .Attr {Name :_dd .Name {Local :"\u0063\u0069\u0064\u003a\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064"},Value :_a .Sprintf ("\u0025\u0076",_dc .DurableIdAttr )});e .EncodeToken (start );e .EncodeToken (_dd .EndElement {Name :start .Name });
return nil ;};func init (){_ag .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073",NewCT_CommentsIds );
_ag .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0043\u0054\u005fC\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064",NewCT_CommentId );
_ag .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","c\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073",NewCommentsIds );
_ag .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0064\u0065c\u0069\u006d\u0061l\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064",NewDecimaldurableId );
};