//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package utils ;import (_d "bytes";_ac "github.com/unidoc/unioffice/v2/document";_dd "github.com/unidoc/unioffice/v2/document/convert";_g "github.com/unidoc/unipdf/v4/model";);

// GetNumPages will try to get actual document page count by converting the document to a PDF first
// and then get the actual page count from the PDF result.
//
// WARNING: This method is currently in experimental state as the PDF result might have incorrect page count.
func GetNumPages (d *_ac .Document )(int ,error ){var _ag _d .Buffer ;_c :=_dd .ConvertToPdf (d );if _ab :=_c .Write (&_ag );_ab !=nil {return 0,_ab ;};_f ,_ge :=_g .NewPdfReader (_d .NewReader (_ag .Bytes ()));if _ge !=nil {return 0,_ge ;};_e ,_ge :=_f .GetNumPages ();
if _ge !=nil {return 0,_ge ;};return _e ,nil ;};