//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package schemaLibrary ;import (_f "encoding/xml";_g "fmt";_cg "github.com/unidoc/unioffice/v2";_c "github.com/unidoc/unioffice/v2/common/logger";);func NewCT_Schema ()*CT_Schema {_ed :=&CT_Schema {};return _ed };

// Validate validates the CT_Schema and its children
func (_ea *CT_Schema )Validate ()error {return _ea .ValidateWithPath ("\u0043T\u005f\u0053\u0063\u0068\u0065\u006da");};type SchemaLibrary struct{CT_SchemaLibrary };

// ValidateWithPath validates the SchemaLibrary and its children, prefixing error messages with path
func (_cb *SchemaLibrary )ValidateWithPath (path string )error {if _dgb :=_cb .CT_SchemaLibrary .ValidateWithPath (path );_dgb !=nil {return _dgb ;};return nil ;};func NewCT_SchemaLibrary ()*CT_SchemaLibrary {_da :=&CT_SchemaLibrary {};return _da };type CT_Schema struct{

// Custom XML Schema Namespace
UriAttr *string ;

// Supplementary XML File Location
ManifestLocationAttr *string ;

// Custom XML Schema Location
SchemaLocationAttr *string ;

// Schema Language
SchemaLanguageAttr *string ;};func (_gac *SchemaLibrary )UnmarshalXML (d *_f .Decoder ,start _f .StartElement )error {_gac .CT_SchemaLibrary =*NewCT_SchemaLibrary ();_bbc :for {_ee ,_ef :=d .Token ();if _ef !=nil {return _ef ;};switch _gd :=_ee .(type ){case _f .StartElement :switch _gd .Name {case _f .Name {Space :"\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067/\u0073\u0063\u0068\u0065\u006da\u004c\u0069\u0062\u0072\u0061\u0072\u0079\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e",Local :"\u0073\u0063\u0068\u0065\u006d\u0061"}:_ac :=NewCT_Schema ();
if _fg :=d .DecodeElement (_ac ,&_gd );_fg !=nil {return _fg ;};_gac .Schema =append (_gac .Schema ,_ac );default:_c .Log .Debug ("\u0073\u006b\u0069\u0070\u0070\u0069\u006e\u0067 \u0075\u006e\u0073up\u0070\u006f\u0072\u0074\u0065\u0064 \u0065\u006c\u0065\u006d\u0065\u006e\u0074\u0020\u006f\u006e\u0020\u0053\u0063\u0068\u0065m\u0061\u004c\u0069\u0062\u0072\u0061\u0072\u0079 \u0025\u0076",_gd .Name );
if _beba :=d .Skip ();_beba !=nil {return _beba ;};};case _f .EndElement :break _bbc ;case _f .CharData :};};return nil ;};type CT_SchemaLibrary struct{

// Custom XML Schema Reference
Schema []*CT_Schema ;};

// Validate validates the CT_SchemaLibrary and its children
func (_dec *CT_SchemaLibrary )Validate ()error {return _dec .ValidateWithPath ("\u0043\u0054_\u0053\u0063\u0068e\u006d\u0061\u004c\u0069\u0062\u0072\u0061\u0072\u0079");};

// Validate validates the SchemaLibrary and its children
func (_gacd *SchemaLibrary )Validate ()error {return _gacd .ValidateWithPath ("\u0053\u0063\u0068\u0065\u006d\u0061\u004c\u0069\u0062\u0072\u0061\u0072\u0079");};

// ValidateWithPath validates the CT_Schema and its children, prefixing error messages with path
func (_de *CT_Schema )ValidateWithPath (path string )error {return nil };func (_d *CT_Schema )MarshalXML (e *_f .Encoder ,start _f .StartElement )error {if _d .UriAttr !=nil {start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u006d\u0061\u003a\u0075\u0072\u0069"},Value :_g .Sprintf ("\u0025\u0076",*_d .UriAttr )});
};if _d .ManifestLocationAttr !=nil {start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u006d\u0061\u003a\u006dan\u0069\u0066\u0065\u0073\u0074\u004c\u006f\u0063\u0061\u0074\u0069\u006f\u006e"},Value :_g .Sprintf ("\u0025\u0076",*_d .ManifestLocationAttr )});
};if _d .SchemaLocationAttr !=nil {start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u006d\u0061\u003a\u0073\u0063\u0068\u0065\u006d\u0061\u004c\u006f\u0063a\u0074\u0069\u006f\u006e"},Value :_g .Sprintf ("\u0025\u0076",*_d .SchemaLocationAttr )});
};if _d .SchemaLanguageAttr !=nil {start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u006d\u0061\u003a\u0073\u0063\u0068\u0065\u006d\u0061\u004c\u0061\u006eg\u0075\u0061\u0067\u0065"},Value :_g .Sprintf ("\u0025\u0076",*_d .SchemaLanguageAttr )});
};e .EncodeToken (start );e .EncodeToken (_f .EndElement {Name :start .Name });return nil ;};func (_edg *CT_SchemaLibrary )UnmarshalXML (d *_f .Decoder ,start _f .StartElement )error {_dd :for {_egc ,_ec :=d .Token ();if _ec !=nil {return _ec ;};switch _gf :=_egc .(type ){case _f .StartElement :switch _gf .Name {case _f .Name {Space :"\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067/\u0073\u0063\u0068\u0065\u006da\u004c\u0069\u0062\u0072\u0061\u0072\u0079\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e",Local :"\u0073\u0063\u0068\u0065\u006d\u0061"}:_dg :=NewCT_Schema ();
if _beb :=d .DecodeElement (_dg ,&_gf );_beb !=nil {return _beb ;};_edg .Schema =append (_edg .Schema ,_dg );default:_c .Log .Debug ("\u0073\u006b\u0069\u0070\u0070i\u006e\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065d\u0020\u0065\u006c\u0065\u006d\u0065\u006e\u0074\u0020\u006f\u006e\u0020\u0043\u0054\u005f\u0053\u0063\u0068\u0065\u006d\u0061\u004c\u0069\u0062\u0072\u0061\u0072\u0079\u0020\u0025v",_gf .Name );
if _cfb :=d .Skip ();_cfb !=nil {return _cfb ;};};case _f .EndElement :break _dd ;case _f .CharData :};};return nil ;};func (_a *SchemaLibrary )MarshalXML (e *_f .Encoder ,start _f .StartElement )error {start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067/\u0073\u0063\u0068\u0065\u006da\u004c\u0069\u0062\u0072\u0061\u0072\u0079\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e"});
start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0078\u006d\u006c\u006e\u0073\u003a\u006d\u0061"},Value :"\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067/\u0073\u0063\u0068\u0065\u006da\u004c\u0069\u0062\u0072\u0061\u0072\u0079\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e"});
start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u006d\u0061:\u0073\u0063\u0068e\u006d\u0061\u004c\u0069\u0062\u0072\u0061\u0072\u0079";return _a .CT_SchemaLibrary .MarshalXML (e ,start );};

// ValidateWithPath validates the CT_SchemaLibrary and its children, prefixing error messages with path
func (_cgc *CT_SchemaLibrary )ValidateWithPath (path string )error {for _bdg ,_db :=range _cgc .Schema {if _bef :=_db .ValidateWithPath (_g .Sprintf ("\u0025\u0073\u002f\u0053\u0063\u0068\u0065\u006d\u0061\u005b\u0025\u0064\u005d",path ,_bdg ));_bef !=nil {return _bef ;
};};return nil ;};func (_ga *CT_Schema )UnmarshalXML (d *_f .Decoder ,start _f .StartElement )error {for _ ,_b :=range start .Attr {if _b .Name .Local =="\u0075\u0072\u0069"{_ge :=_b .Value ;_ga .UriAttr =&_ge ;continue ;};if _b .Name .Local =="\u006d\u0061n\u0069\u0066\u0065s\u0074\u004c\u006f\u0063\u0061\u0074\u0069\u006f\u006e"{_fe :=_b .Value ;
_ga .ManifestLocationAttr =&_fe ;continue ;};if _b .Name .Local =="\u0073\u0063\u0068\u0065\u006d\u0061\u004c\u006f\u0063a\u0074\u0069\u006f\u006e"{_cd :=_b .Value ;_ga .SchemaLocationAttr =&_cd ;continue ;};if _b .Name .Local =="\u0073\u0063\u0068\u0065\u006d\u0061\u004c\u0061\u006eg\u0075\u0061\u0067\u0065"{_eb :=_b .Value ;
_ga .SchemaLanguageAttr =&_eb ;continue ;};};for {_bb ,_be :=d .Token ();if _be !=nil {return _g .Errorf ("p\u0061\u0072\u0073\u0069ng\u0020C\u0054\u005f\u0053\u0063\u0068e\u006d\u0061\u003a\u0020\u0025\u0073",_be );};if _cf ,_bd :=_bb .(_f .EndElement );
_bd &&_cf .Name ==start .Name {break ;};};return nil ;};func (_cdc *CT_SchemaLibrary )MarshalXML (e *_f .Encoder ,start _f .StartElement )error {e .EncodeToken (start );if _cdc .Schema !=nil {_gef :=_f .StartElement {Name :_f .Name {Local :"\u006da\u003a\u0073\u0063\u0068\u0065\u006da"}};
for _ ,_bg :=range _cdc .Schema {e .EncodeElement (_bg ,_gef );};};e .EncodeToken (_f .EndElement {Name :start .Name });return nil ;};func NewSchemaLibrary ()*SchemaLibrary {_gc :=&SchemaLibrary {};_gc .CT_SchemaLibrary =*NewCT_SchemaLibrary ();return _gc ;
};func init (){_cg .RegisterConstructor ("\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067/\u0073\u0063\u0068\u0065\u006da\u004c\u0069\u0062\u0072\u0061\u0072\u0079\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e","\u0043T\u005f\u0053\u0063\u0068\u0065\u006da",NewCT_Schema );
_cg .RegisterConstructor ("\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067/\u0073\u0063\u0068\u0065\u006da\u004c\u0069\u0062\u0072\u0061\u0072\u0079\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e","\u0043\u0054_\u0053\u0063\u0068e\u006d\u0061\u004c\u0069\u0062\u0072\u0061\u0072\u0079",NewCT_SchemaLibrary );
_cg .RegisterConstructor ("\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067/\u0073\u0063\u0068\u0065\u006da\u004c\u0069\u0062\u0072\u0061\u0072\u0079\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e","\u0073\u0063\u0068\u0065\u006d\u0061\u004c\u0069\u0062\u0072\u0061\u0072\u0079",NewSchemaLibrary );
};