//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package wordprocessingDrawing ;import (_c "encoding/xml";_b "fmt";_g "github.com/unidoc/unioffice/v2";_ca "strconv";);func (_d *CT_WebVideoPr )MarshalXML (e *_c .Encoder ,start _c .StartElement )error {if _d .EmbeddedHtmlAttr !=nil {start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0065\u006d\u0062e\u0064\u0064\u0065\u0064\u0048\u0074\u006d\u006c"},Value :_b .Sprintf ("\u0025\u0076",*_d .EmbeddedHtmlAttr )});
};if _d .HAttr !=nil {start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0068"},Value :_b .Sprintf ("\u0025\u0076",*_d .HAttr )});};if _d .WAttr !=nil {start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0077"},Value :_b .Sprintf ("\u0025\u0076",*_d .WAttr )});
};e .EncodeToken (start );e .EncodeToken (_c .EndElement {Name :start .Name });return nil ;};func NewWebVideoPr ()*WebVideoPr {_ba :=&WebVideoPr {};_ba .CT_WebVideoPr =*NewCT_WebVideoPr ();return _ba ;};func NewCT_WebVideoPr ()*CT_WebVideoPr {_ce :=&CT_WebVideoPr {};
return _ce };type CT_WebVideoPr struct{EmbeddedHtmlAttr *string ;HAttr *uint32 ;WAttr *uint32 ;};

// ValidateWithPath validates the CT_WebVideoPr and its children, prefixing error messages with path
func (_fe *CT_WebVideoPr )ValidateWithPath (path string )error {return nil };type WebVideoPr struct{CT_WebVideoPr };

// ValidateWithPath validates the WebVideoPr and its children, prefixing error messages with path
func (_ceg *WebVideoPr )ValidateWithPath (path string )error {if _bg :=_ceg .CT_WebVideoPr .ValidateWithPath (path );_bg !=nil {return _bg ;};return nil ;};func (_baa *WebVideoPr )MarshalXML (e *_c .Encoder ,start _c .StartElement )error {start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068\u0065\u006da\u0073\u002e\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006fr\u0064\u002f\u0032\u0030\u0031\u0032\u002f\u0077\u006f\u0072\u0064\u0070\u0072\u006f\u0063e\u0073\u0073\u0069\u006e\u0067\u0044\u0072\u0061w\u0069\u006e\u0067"});
start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0077\u0065\u0062\u0056\u0069\u0064\u0065\u006f\u0050\u0072";return _baa .CT_WebVideoPr .MarshalXML (e ,start );};func (_de *CT_WebVideoPr )UnmarshalXML (d *_c .Decoder ,start _c .StartElement )error {for _ ,_f :=range start .Attr {if _f .Name .Local =="\u0065\u006d\u0062e\u0064\u0064\u0065\u0064\u0048\u0074\u006d\u006c"{_e :=_f .Value ;
_de .EmbeddedHtmlAttr =&_e ;continue ;};if _f .Name .Local =="\u0068"{_af ,_bf :=_ca .ParseUint (_f .Value ,10,32);if _bf !=nil {return _bf ;};_bb :=uint32 (_af );_de .HAttr =&_bb ;continue ;};if _f .Name .Local =="\u0077"{_cef ,_ac :=_ca .ParseUint (_f .Value ,10,32);
if _ac !=nil {return _ac ;};_ea :=uint32 (_cef );_de .WAttr =&_ea ;continue ;};};for {_dg ,_fb :=d .Token ();if _fb !=nil {return _b .Errorf ("\u0070a\u0072\u0073\u0069\u006eg\u0020\u0043\u0054\u005f\u0057e\u0062V\u0069d\u0065\u006f\u0050\u0072\u003a\u0020\u0025s",_fb );
};if _fa ,_cf :=_dg .(_c .EndElement );_cf &&_fa .Name ==start .Name {break ;};};return nil ;};

// Validate validates the CT_WebVideoPr and its children
func (_eb *CT_WebVideoPr )Validate ()error {return _eb .ValidateWithPath ("\u0043\u0054\u005f\u0057\u0065\u0062\u0056\u0069\u0064\u0065\u006f\u0050\u0072");};func (_bbf *WebVideoPr )UnmarshalXML (d *_c .Decoder ,start _c .StartElement )error {_bbf .CT_WebVideoPr =*NewCT_WebVideoPr ();
for _ ,_gf :=range start .Attr {if _gf .Name .Local =="\u0065\u006d\u0062e\u0064\u0064\u0065\u0064\u0048\u0074\u006d\u006c"{_dgd :=_gf .Value ;_bbf .EmbeddedHtmlAttr =&_dgd ;continue ;};if _gf .Name .Local =="\u0068"{_aa ,_gb :=_ca .ParseUint (_gf .Value ,10,32);
if _gb !=nil {return _gb ;};_acc :=uint32 (_aa );_bbf .HAttr =&_acc ;continue ;};if _gf .Name .Local =="\u0077"{_baac ,_bbg :=_ca .ParseUint (_gf .Value ,10,32);if _bbg !=nil {return _bbg ;};_cd :=uint32 (_baac );_bbf .WAttr =&_cd ;continue ;};};for {_dea ,_bbb :=d .Token ();
if _bbb !=nil {return _b .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0057\u0065\u0062\u0056\u0069\u0064\u0065\u006f\u0050\u0072\u003a\u0020%\u0073",_bbb );};if _cg ,_db :=_dea .(_c .EndElement );_db &&_cg .Name ==start .Name {break ;};};return nil ;
};

// Validate validates the WebVideoPr and its children
func (_fc *WebVideoPr )Validate ()error {return _fc .ValidateWithPath ("\u0057\u0065\u0062\u0056\u0069\u0064\u0065\u006f\u0050\u0072");};func init (){_g .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068\u0065\u006da\u0073\u002e\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006fr\u0064\u002f\u0032\u0030\u0031\u0032\u002f\u0077\u006f\u0072\u0064\u0070\u0072\u006f\u0063e\u0073\u0073\u0069\u006e\u0067\u0044\u0072\u0061w\u0069\u006e\u0067","\u0043\u0054\u005f\u0057\u0065\u0062\u0056\u0069\u0064\u0065\u006f\u0050\u0072",NewCT_WebVideoPr );
_g .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068\u0065\u006da\u0073\u002e\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006fr\u0064\u002f\u0032\u0030\u0031\u0032\u002f\u0077\u006f\u0072\u0064\u0070\u0072\u006f\u0063e\u0073\u0073\u0069\u006e\u0067\u0044\u0072\u0061w\u0069\u006e\u0067","\u0077\u0065\u0062\u0056\u0069\u0064\u0065\u006f\u0050\u0072",NewWebVideoPr );
};