//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package picture ;import (_a "encoding/xml";_b "fmt";_f "github.com/unidoc/unioffice/v2";_be "github.com/unidoc/unioffice/v2/schema/soo/dml";);

// Validate validates the ExtLst and its children
func (_ege *ExtLst )Validate ()error {return _ege .ValidateWithPath ("\u0045\u0078\u0074\u004c\u0073\u0074");};func (_ea *Style )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_ea .CT_ShapeStyle =*_be .NewCT_ShapeStyle ();for {_ge ,_ca :=d .Token ();
if _ca !=nil {return _b .Errorf ("\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0053\u0074\u0079\u006ce\u003a\u0020\u0025\u0073",_ca );};if _dg ,_ff :=_ge .(_a .EndElement );_ff &&_dg .Name ==start .Name {break ;};};return nil ;};func (_e *ExtLst )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_e .CT_OfficeArtExtensionList =*_be .NewCT_OfficeArtExtensionList ();
for {_eg ,_bf :=d .Token ();if _bf !=nil {return _b .Errorf ("\u0070a\u0072s\u0069\u006e\u0067\u0020\u0045x\u0074\u004cs\u0074\u003a\u0020\u0025\u0073",_bf );};if _bff ,_fc :=_eg .(_a .EndElement );_fc &&_bff .Name ==start .Name {break ;};};return nil ;
};

// ValidateWithPath validates the Style and its children, prefixing error messages with path
func (_ga *Style )ValidateWithPath (path string )error {if _dfg :=_ga .CT_ShapeStyle .ValidateWithPath (path );_dfg !=nil {return _dfg ;};return nil ;};

// Validate validates the Style and its children
func (_df *Style )Validate ()error {return _df .ValidateWithPath ("\u0053\u0074\u0079l\u0065")};type ExtLst struct{_be .CT_OfficeArtExtensionList };func (_c *Style )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0070\u0069\u0063\u0074\u0075\u0072\u0065"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0073\u0074\u0079l\u0065";return _c .CT_ShapeStyle .MarshalXML (e ,start );};func NewExtLst ()*ExtLst {_d :=&ExtLst {};_d .CT_OfficeArtExtensionList =*_be .NewCT_OfficeArtExtensionList ();return _d ;};func (_fe *ExtLst )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0070\u0069\u0063\u0074\u0075\u0072\u0065"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0065\u0078\u0074\u004c\u0073\u0074";return _fe .CT_OfficeArtExtensionList .MarshalXML (e ,start );};type Style struct{_be .CT_ShapeStyle };func NewStyle ()*Style {_ab :=&Style {};_ab .CT_ShapeStyle =*_be .NewCT_ShapeStyle ();return _ab };


// ValidateWithPath validates the ExtLst and its children, prefixing error messages with path
func (_de *ExtLst )ValidateWithPath (path string )error {if _ee :=_de .CT_OfficeArtExtensionList .ValidateWithPath (path );_ee !=nil {return _ee ;};return nil ;};func init (){_f .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0070\u0069\u0063\u0074\u0075\u0072\u0065","\u0073\u0074\u0079l\u0065",NewStyle );
_f .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0070\u0069\u0063\u0074\u0075\u0072\u0065","\u0065\u0078\u0074\u004c\u0073\u0074",NewExtLst );
};